### ISSUE TITLE
大佬，你的源码编译后无执行权限，我重新写了一个赋予执行权限的makefile

### ISSUE THREAD

**Issue by zxlhhyccc** [tty228/luci-app-serverchan#1]

**Comment by ydch** [comment]
编译后的确无执行权限。你的makefile能看看吗

**Comment by zxlhhyccc** [comment]
> 编译后的确无执行权限。你的makefile能看看吗

怎么看？

**Comment by ZeaKyX** [comment]
> 编译后的确无执行权限。你的makefile能看看吗

不知你解决没有，把chmod改成755应该就行

**Comment by zxlhhyccc** [comment]
> > 编译后的确无执行权限。你的makefile能看看吗
> 
> 不知你解决没有，把chmod改成755应该就行

改成755也是没用，我另外写了makefile

**Comment by zxlhhyccc** [comment]
# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-serverchan
PKG_VERSION:=1.0
PKG_RELEASE:=40

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/luci-app-serverchan
	SECTION:=luci
	CATEGORY:=LuCI
	SUBMENU:=3. Applications
	TITLE:=LuCI Support for serverchan on or off
	DEPENDS:=+iputils-arping +curl
endef

define Package/luci-app-serverchan/description
	LuCI support for serverchan
endef

define Build/Prepare
endef

define Build/Compile
endef

define Package/luci-app-serverchan/install
	$(INSTALL_DIR) $(1)/usr/lib/lua/luci
	cp -pR ./luasrc/* $(1)/usr/lib/lua/luci
	$(INSTALL_DIR) $(1)/
	cp -pR ./root/* $(1)/
endef

define Package/luci-app-serverchan/postinst
#!/bin/sh
	chmod 755 /etc/init.d/serverchan >/dev/null 2>&1
	chmod 755 /usr/bin/serverchan/serverchan >/dev/null 2>&1
	/etc/init.d/serverchan enable >/dev/null 2>&1
exit 0
endef

define Package/luci-app-serverchan/prerm
#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
     /etc/init.d/serverchan disable
     /etc/init.d/serverchan stop
fi
exit 0
endef

$(eval $(call BuildPackage,luci-app-serverchan))
拿去用吧。。。。

**Comment by zxlhhyccc** [comment]
> > 编译后的确无执行权限。你的makefile能看看吗
> 
> 不知你解决没有，把chmod改成755应该就行

也可以在这里pull我的修改后的：
https://github.com/zxlhhyccc/luci-app-serverchan

**Comment by ZeaKyX** [comment]
> > > 编译后的确无执行权限。你的makefile能看看吗
> > 
> > 
> > 不知你解决没有，把chmod改成755应该就行
> 
> 也可以在这里pull我的修改后的：
> https://github.com/zxlhhyccc/luci-app-serverchan

多谢

**Comment by hong0980** [comment]
大佬路由器的上传下载的流量能写进去吗

**Comment by tty228** [comment]
好的，你提交一下还是我直接改了

**Comment by hong0980** [comment]
> 好的，你提交一下还是我直接改了

大佬还是你修改下，有空顺便把路由器的上传下载的流量推送能写进去。期待新版！！！！

**Comment by rhww** [comment]
> > > 编译后的确无执行权限。你的makefile能看看吗
> > 
> > 
> > 不知你解决没有，把chmod改成755应该就行
> 
> 也可以在这里pull我的修改后的：
> https://github.com/zxlhhyccc/luci-app-serverchan

我用你的也不能运行，尴尬啊。

**Comment by hong0980** [comment]
> > > > 编译后的确无执行权限。你的makefile能看看吗
> > > 
> > > 
> > > 不知你解决没有，把chmod改成755应该就行
> > 
> > 
> > 也可以在这里pull我的修改后的：
> > https://github.com/zxlhhyccc/luci-app-serverchan
> 
> 我用你的也不能运行，尴尬啊。

`# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-serverchan
PKG_VERSION:=1.0
PKG_RELEASE:=50

PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/luci-app-serverchan
	SECTION:=luci
	CATEGORY:=LuCI
	SUBMENU:=3. Applications
	TITLE:=LuCI Support for serverchan on or off
	DEPENDS:=+iputils-arping +curl
endef

define Package/luci-app-serverchan/description
	LuCI support for serverchan
endef

define Build/Prepare
endef

define Build/Compile
endef

define Package/luci-app-serverchan/install
	$(INSTALL_DIR) $(1)/usr/lib/lua/luci
	cp -pR ./luasrc/* $(1)/usr/lib/lua/luci
	$(INSTALL_DIR) $(1)/
	cp -pR ./root/* $(1)/
endef

define Package/$(PKG_NAME)/postinst
#!/bin/sh
	chmod 755 $${IPKG_INSTROOT}/etc/init.d/serverchan >/dev/null 2>&1
	chmod 755 $${IPKG_INSTROOT}/usr/bin/serverchan/serverchan >/dev/null 2>&1
	/etc/init.d/serverchan enable >/dev/null 2>&1
exit 0
endef

define Package/luci-app-serverchan/prerm
#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
     /etc/init.d/serverchan disable
     /etc/init.d/serverchan stop
fi
exit 0
endef

$(eval $(call BuildPackage,luci-app-serverchan))`
