### ISSUE TITLE
安装到潘多拉能启动，但是无法推送

### ISSUE THREAD

**Issue by zsx626** [tty228/luci-app-serverchan#10]
安装到潘多拉能启动，但是无法推送，不知道什么原因

**Comment by tty228** [comment]
脚本依赖
iputils-arping +curl 
arping 不知道潘多拉支不支持，使用arp检测在线设备是因为避免WiFi休眠时设备无法检测
如果能运行的话，打开日志查看错误，自行修改代码

**Comment by zsx626** [comment]
已解决，多谢，把开头sh改成bash正常推送

**Comment by iori8421** [comment]
可以提供一下编译好的ipk文件吗

**Comment by zsx626** [comment]
> 可以提供一下编译好的ipk文件吗

https://www.right.com.cn/forum/thread-988187-1-1.html

**Comment by wujunze** [comment]
> 安装到潘多拉能启动，但是无法推送，不知道什么原因

你好  你的 PandoraBox  固件版本多少
