### ISSUE TITLE
IPV6变动没有通知

### ISSUE THREAD

**Issue by michzp88** [tty228/luci-app-serverchan#101]
N1盒子刷的OpenWrt固件Luci Master，上的serverchan插件设置，IPV6变动通知，因为固件不支持IPV6，所以选择的通过URL获取（电脑打开获取网址，可以正常取到IPV6的地址），但好像IP变动没有任何通知，这是什么原因？

**Comment by tty228** [comment]
之前的默认地址好像失效了，现在不知道正常了没有

**Comment by tty228** [comment]
我这边没有 ipv6 没法测试网站 api
