### ISSUE TITLE
serverchan安装到基于lean源码编译X86-64固件，luci反馈安装错误，并且设备可以运行但是日记提示网络不通

### ISSUE THREAD

**Issue by eternalfor** [tty228/luci-app-serverchan#104]
安装后luci界面反馈错误信息如下：
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/system/filetransfer'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/updownload.lua:155: bad argument #2 to 'format' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

软件日记记录如下：
2020-09-27 22:40:34 【！！！】未安装 wrtbwmon ，流量统计不可用
2020-09-27 22:40:34 【初始化】载入在线设备
2020-09-27 22:41:30 【！！！】未安装 wrtbwmon ，流量统计不可用
2020-09-27 22:41:30 【初始化】载入在线设备
2020-09-27 22:41:37 【初始化】初始化完成
2020-09-27 22:41:37 【！！！！】当前网络不通！停止检测！

**Comment by alipapabi** [comment]
我也遇到相同的问题。。。求大神处理一下 X86平台 OPENWRT

**Comment by tty228** [comment]
尝试使用 sh -x /usr/bin/serverchan/serverchan 
可能是 curl 命令出错

**Comment by alipapabi** [comment]
> sh -x /usr/bin/serverchan/serverchan

+ rand_geturl
+ local 'urllist=https://www.163.com https://www.qq.com https://www.baidu.com https://www.qidian.com https://www.douban.com'
+ echo 'https://www.163.com https://www.qq.com https://www.baidu.com https://www.qidian.com https://www.douban.com'
+ awk 'BEGIN{srand();sum=rand()*5+ 1;printf("%d",sum)}'
+ awk -v 'i=5' '{print $i}'
+ local 'url_str=https://www.douban.com'
+ getcheck
+ curl -k -s -w '%{http_code}' https://www.douban.com -A 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11' -o /dev/null
Error loading shared library libwolfssl.so.24: No such file or directory (needed by /usr/bin/curl)
+ echo
+ local 'check='
+ '[' -z  ]
+ getcheck
+ curl -k -s -w '%{http_code}' https://www.douban.com -A 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11' -o /dev/null
Error loading shared library libwolfssl.so.24: No such file or directory (needed by /usr/bin/curl)
+ echo
+ local 'check='
+ '[' '!' -z  ]
+ '[' -z  ]
+ date '+%Y-%m-%d %H:%M:%S'
+ echo '2020-10-28 17:10:22 【！！！！】当前网络不通！停止检测！ '
+ local 'network_enable=404'
+ '[' -z  ]
+ date '+%s'
+ network_err_time=1603876222
+ '[' '!' -z  ]

大神您好，运行命令以后提示这样的~~能否帮看看是什么问题

**Comment by tty228** [comment]
Error loading shared library libwolfssl.so.24: No such file or directory (needed by /usr/bin/curl)

查看是否安装 curl

**Comment by zfnu** [comment]
把curl和libcurl4卸载，再重新安装，解决

**Comment by eternalfor** [comment]
感谢，解决问题
