### ISSUE TITLE
lede x86，N1均编译出错

### ISSUE THREAD

**Issue by HoldOnBro** [tty228/luci-app-serverchan#108]
install: cannot create regular file '/workdir/openwrt/build_dir/target-aarch64_generic_musl/luci-app-serverchan-1.78/.pkgdir/luci-app-serverchan/usr/share/rpcd/acl.d/luci-app-serverchan.json': No such file or directory
Makefile:40: recipe for target '/workdir/openwrt/build_dir/target-aarch64_generic_musl/luci-app-serverchan-1.78/.pkgdir/luci-app-serverchan.installed' failed
make[3]: *** [/workdir/openwrt/build_dir/target-aarch64_generic_musl/luci-app-serverchan-1.78/.pkgdir/luci-app-serverchan.installed] Error 1
make[3]: Leaving directory '/workdir/openwrt/package/luci-app-serverchan'
time: package/luci-app-serverchan/compile#0.14#0.05#0.20
package/Makefile:111: recipe for target 'package/luci-app-serverchan/compile' failed

**Comment by liuran001** [comment]
一样的错误

**Comment by HoldOnBro** [comment]
[#107 ](https://github.com/tty228/luci-app-serverchan/pull/107) 解决了
