### ISSUE TITLE
请教代码的作用

### ISSUE THREAD

**Issue by Twinzo1** [tty228/luci-app-serverchan#109]
请问在[root/usr/bin/serverchan/serverchann](https://github.com/tty228/luci-app-serverchan/blob/6387b3b47b03d95d3f3bcd42ff98db5bb84fd056/root/usr/bin/serverchan/serverchan)的```39-41```行的作用是什么
```
for read_str in "ip_version" "cu_version"; do
	[ -z `eval echo '$'$read_str` ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】依赖项未安装" >> ${logfile} && return 1
done
```
在x86中不能启动，就是因为这里return了，注释掉后就没有问题
环境：32位N270 5.4.51内核自编译lean lede
--

**Comment by tty228** [comment]
14行
`
	for str_version in "wrtbwmon" "iputils-arping" "curl" "iw"; do
		eval `echo ${str_version:0:2}"_version"`=`opkg list-installed|grep -w ^${str_version}|awk '{print $3}'` 2>/dev/null
	done
`

从 软件包列表中 读取 wrtbwmon 、iputils-arping、curl、 iw 依赖项的名称和版本号，如果存在，创建变量 软件名前两位_version

在

`
for read_str in "ip_version" "cu_version"; do
	[ -z `eval echo '$'$read_str` ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】依赖项未安装" >> ${logfile} && return 1
done
`

中检查变量是否存在，因为有段时间，有的机型不知为何没有安装依赖还是编译成功了，所以加入了以上代码，确认依赖有安装的话可以注释掉

wrtbwmon 用于流量统计（硬件加速、软件加速环境中无法工作）
iputils-arping 用于探测设备是否下线，因为使用 ping 命令检查无法 ping 通休眠设备
curl 用于推送、检查网络状态等
iw 用于检查设备是否与路由 wifi 连接，如果有则跳过 ping ，但是有的软路由没有网卡，如果未安装，则不进行此检测


因为是使用软件名检测，可能 x86 环境中这两个依赖项的名称做了改变
