### ISSUE TITLE
r2s安装故障

### ISSUE THREAD

**Issue by alipapabi** [tty228/luci-app-serverchan#112]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/system/filetransfer'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/updownload.lua:155: bad argument #2 to 'format' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by bike3097a** [comment]
我这边安装完，返回一切正常

**Comment by gyc98** [comment]
r2s没问题，我这正常
