### ISSUE TITLE
安装时候提示错误 我是的X86_64的系统，软路由

### ISSUE THREAD

**Issue by alipapabi** [tty228/luci-app-serverchan#117]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/system/filetransfer'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/updownload.lua:155: bad argument #2 to 'format' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by tty228** [comment]
我这边没法复现这个问题
