### ISSUE TITLE
脚本指示状态错误

### ISSUE THREAD

**Issue by lqh9724** [tty228/luci-app-serverchan#119]
平台：x86软路由，插件安装方式：编译安装。
主机信息：
【主机名 | OpenWrt
-- | --
主机型号 | Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz : 1 Core 1 Thread (CpuMark : 24950.391604 Scores)
CPU 信息 | 3292.376 MHz
固件版本 | OpenWrt R20.10.20 / LuCI Master (git-20.343.54716-6fc079f)
内核版本 | 5.4.79
本地时间 | Fri Dec 25 13:29:51 2020
运行时间 | 0h 54m 49s
平均负载 | 0.12, 0.24, 0.20
CPU 使用率（%） | 0 %】
-----------------------------------------------
错误提示：serverchan运行状态为：serverchan停止运行；
实际状态：serverchan依然在运行。设置了定时推送路由器信息也能很准时的推送到位。
可能的错误原因：免打扰设置中使用了模式一“挂起脚本”。实际测试中，切换为模式二“静默模式“经过了免打扰时间段以后脚本运行状态指示是正常的；可能是模式一脚本挂起以后恢复运行时没有正确的反馈的运行状态。

**Comment by lqh9724** [comment]
另外。在使用openclash的fakeip模式下，读取的外网IP为空。
获取IP方式：通过wan口pppoe获取；
可以正常且正确获取接口IP地址（公网地址），第二项提示”外网IP“值为空不显示；
关闭openclash，即可恢复正常。
![image](https://user-images.githubusercontent.com/38914772/103121451-29d95300-46b7-11eb-87fa-d11dbec9bea9.png)

--------------------------------------
已知cloudflare的ddns服务在fakeip模式下也会出错，无法获取正确的IP；将需要绑定ddns的域名添加到openclash的”全局设置-dns设置-高级设置“下的fakeip黑名单中即可正常且正确获取IP地址。

**Comment by trotack** [comment]
我也遇到同样的情况。Openclash在fakeip模式下，推送通知所获取到的外网IP为空。我记得在某个版本之前是正常的。但我觉得大概率问题还是出在openclash端。因为关闭openclash就一切正常。

**Comment by trotack** [comment]
将93行的
[ ! -z "$ipv4_interface" ] && local hostIP=$(curl -k -s -4 --interface ${ipv4_interface} ${ipv4_URL}) || local hostIP=$(curl -k -s -4 ${ipv4_URL})
修改为                                   
[ ! -z "$ipv4_interface" ] && local hostIP=$(curl -k -s -4 ${ipv4_URL})
之后正常，开着openclash也正常。

**Comment by lqh9724** [comment]
> 将93行的
> [ ! -z "$ipv4_interface" ] && local hostIP=$(curl -k -s -4 --interface ${ipv4_interface} ${ipv4_URL}) || local hostIP=$(curl -k -s -4 ${ipv4_URL})
> 修改为
> [ ! -z "$ipv4_interface" ] && local hostIP=$(curl -k -s -4 ${ipv4_URL})
> 之后正常，开着openclash也正常。

这是个不错的解决方案，非常感谢。猜想是因为open clash劫持本地dns，若是用openwrt拨号上网的情况下，其实接口IP和外网IP是一致的，这个问题并不影响最后的信息真实性。
