### ISSUE TITLE
设备列表问题 

### ISSUE THREAD

**Issue by hyird** [tty228/luci-app-serverchan#12]
大佬 你的那个 设备列表 是通过arp表来获取的把 这样 我的网络环境下 直接把 eth0的也算进去了
所以 客户端 会莫名其妙多一个  
可以
IPLIST=$( cat /proc/net/arp | grep "0x2" | awk  '{print $1}' | grep -v "^$" | sort -u )
修改为
IPLIST=$( cat /proc/net/arp | grep br-lan |grep "0x2" | awk  '{print $1}' | grep -v "^$" | sort -u )

**Comment by ZeaKyX** [comment]
> 大佬 你的那个 设备列表 是通过arp表来获取的把 这样 我的网络环境下 直接把 eth0的也算进去了
> 所以 客户端 会莫名其妙多一个
> 可以
> IPLIST=$( cat /proc/net/arp | grep "0x2" | awk '{print $1}' | grep -v "^$" | sort -u )
> 修改为
> IPLIST=$( cat /proc/net/arp | grep br-lan |grep "0x2" | awk '{print $1}' | grep -v "^$" | sort -u )

你好，我想请问一下设备列表刷新的问题，我看到设备上下线有一段/var/dhcp.leases来实现的，不知道这个的刷新时间是多久，我在用padavan的时候设备下线dhcp刷新要将近十分钟。但是后面又有一段arp的判断代码，如果用arp据说刷新时间是30s那就很好，不知道这里到底是怎么判断的？

**Comment by vergessenlzx** [comment]
> > 大佬 你的那个 设备列表 是通过arp表来获取的把 这样 我的网络环境下 直接把 eth0的也算进去了
> > 所以 客户端 会莫名其妙多一个
> > 可以
> > IPLIST=$( cat /proc/net/arp | grep "0x2" | awk '{print $1}' | grep -v "^$" | sort -u )
> > 修改为
> > IPLIST=$( cat /proc/net/arp | grep br-lan |grep "0x2" | awk '{print $1}' | grep -v "^$" | sort -u )
> 
> 你好，我想请问一下设备列表刷新的问题，我看到设备上下线有一段/var/dhcp.leases来实现的，不知道这个的刷新时间是多久，我在用padavan的时候设备下线dhcp刷新要将近十分钟。但是后面又有一段arp的判断代码，如果用arp据说刷新时间是30s那就很好，不知道这里到底是怎么判断的？

我没太 仔细看  但是 设备上下线 可以通过 arp 的flags判断 0x2在线 0x0离线 响应是很快的

**Comment by tty228** [comment]
dhcp 主要是用来获取设备名
arp 是为了避免休眠设备检测为离线，ping 命令设备锁屏后会 ping 不通
ping 是因为设备离线时，想要手动删除 arp表 中的离线设备（精简 arp表 节约检测时间），但是好像 openwrt 这个命令无效，反而在使用 ping 命令，ping 不通时，会自动删除 arp表，很迷……
检测设备在线状态主要是主动 ping ，所以和列表文件无关，默认为一分钟一次

**Comment by tty228** [comment]
grep br-lan 这个你知道添加的话，我就不修改代码了，我这边的网络环境接口比较多，不能只检测 br-lan 接口，你不修改代码的话，可以使用白名单只检测 br-lan 接口
