### ISSUE TITLE
那个TG推送，怎么还要拉入群组，能不能类似这种，直接BOT 发信息给我

### ISSUE THREAD

**Issue by mjyhj** [tty228/luci-app-serverchan#128]
https://gitee.com/lxk0301/jd_docker/blob/master/backUp/TG_PUSH.md
只需要填写：TG_BOT_TOKEN以及TG_USER_ID
![1](https://user-images.githubusercontent.com/22577418/111753307-ad2ecd00-88d1-11eb-9a19-634e0ead519c.png)

**Comment by tty228** [comment]
直接把 TG_USER_ID 填进去就行了
我之前测试的时候没推送，可能是没开启对话，一会我再改说明吧
