### ISSUE TITLE
怎么老是显示红色的“serverchan NOT RUNNING”呢

### ISSUE THREAD

**Issue by irrocu** [tty228/luci-app-serverchan#130]
![Snipaste_2021-03-21_01-33-48](https://user-images.githubusercontent.com/66506186/111881292-beb7c800-89ea-11eb-92a9-5c95baf38d87.jpg)
程序运行一切正常，就是“serverchan NOT RUNNING“会经常出现。如上图。

**Comment by tty228** [comment]
运行 `ps|grep -v grep|grep -c serverchan`
查看返回数据
这个命令存在于
/usr/lib/lua/luci/controller/serverchan.lua 文件

**Comment by irrocu** [comment]
已经OK了，非常感谢。
我也不知道是什么原因，刚安装的时候只有点手工发送消息的时候才出现绿色的“serverchan  RUNNING“，发送完毕后又变成了红色的“serverchan NOT RUNNING“。当时我用的是企业版的server酱。

现在我用的是公众号版的server酱。
目前一切正常，显示绿色的“serverchan  RUNNING“
![Snipaste_2021-03-23_16-12-56](https://user-images.githubusercontent.com/66506186/112114786-69023c00-8bf3-11eb-8f71-a9a6ff9f3b3d.jpg)
![Snipaste_2021-03-23_16-13-46](https://user-images.githubusercontent.com/66506186/112114800-6bfd2c80-8bf3-11eb-945e-1567c14baacb.jpg)

**Comment by magihub** [comment]
> 运行 `ps|grep -v grep|grep -c serverchan`
> 查看返回数据
> 这个命令存在于
> /usr/lib/lua/luci/controller/serverchan.lua 文件

我在R2S上自行安装的serverchan（原固件未集成），也是显示红色的“serverchan未运行”，运行上述命令，返回数据为0，不知其意，求解释。
![QQ截图20210323201706](https://user-images.githubusercontent.com/77531918/112145284-1fc2e400-8c15-11eb-9571-433772274626.png)
![QQ截图20210323201619](https://user-images.githubusercontent.com/77531918/112145294-23566b00-8c15-11eb-8f56-81f97ed9c1ef.png)

**Comment by magihub** [comment]
> 已经OK了，非常感谢。
> 我也不知道是什么原因，刚安装的时候只有点手工发送消息的时候才出现绿色的“serverchan RUNNING“，发送完毕后又变成了红色的“serverchan NOT RUNNING“。当时我用的是企业版的server酱。
> 
> 现在我用的是公众号版的server酱。
> 目前一切正常，显示绿色的“serverchan RUNNING“


我用的也是公众号的呀，你是怎么解决的？求告知，谢谢。

**Comment by irrocu** [comment]
@magihub 可能因为你是arm版的软路由吧，我是X86的，我所做的都写在上面了。

**Comment by magihub** [comment]
@irrocu 好的 谢谢 我只能等作者回复了 你只是从企业版切换到了公众号版就行了 对吗？

**Comment by irrocu** [comment]
@magihub 是的，我虽然当时经常显示的是红色，但是能正常使用，你能正常使用吗

**Comment by magihub** [comment]
不能

 
发件人： irrocu
发送时间： 2021-03-24 12:53
收件人： tty228/luci-app-serverchan
抄送： magihub; Mention
主题： Re: [tty228/luci-app-serverchan] 怎么老是显示红色的“serverchan NOT RUNNING”呢 (#130)
@magihub 是的，我虽然当时经常显示的是红色，但是能正常使用，你能正常使用吗

**Comment by irrocu** [comment]
@magihub 建议你用tg bot试试看，先运行起来

**Comment by magihub** [comment]
我在京东签到里有设置serverchan的推送，目前是可以正常推用的；但独立的这个“微信推送”模块却不行，使用的是同一个SCKEY代码

**Comment by jxph1123** [comment]
应该是一些组件不兼容，我之前直接安装的，自己安装了curl等，结果也是不能使用，后面我自己编译到了lean的源码里面，可用了。。

**Comment by magihub** [comment]
> 应该是一些组件不兼容，我之前直接安装的，自己安装了curl等，结果也是不能使用，后面我自己编译到了lean的源码里面，可用了。。

感谢 可我自己还不会编译 尝试了几次都没成功

**Comment by tty228** [comment]
> > 运行 `ps|grep -v grep|grep -c serverchan`
> > 查看返回数据
> > 这个命令存在于
> > /usr/lib/lua/luci/controller/serverchan.lua 文件
> 
> 我在R2S上自行安装的serverchan（原固件未集成），也是显示红色的“serverchan未运行”，运行上述命令，返回数据为0，不知其意，求解释。
> ![QQ截图20210323201706](https://user-images.githubusercontent.com/77531918/112145284-1fc2e400-8c15-11eb-9571-433772274626.png)
> ![QQ截图20210323201619](https://user-images.githubusercontent.com/77531918/112145294-23566b00-8c15-11eb-8f56-81f97ed9c1ef.png)

ps  查看系统进程列表
ps|grep -v grep  查看系统进程列表，并去除包含grep的进程行
ps|grep -v grep|grep -c serverchan  查看系统进程中 serverchan 的行数

建议自行替换命令，我不知道你那边的环境

**Comment by tty228** [comment]
你试试
`top -bn1 | grep -v 'grep' | grep -c 'serverchan'`

**Comment by magihub** [comment]
> 你试试
> `top -bn1 | grep -v 'grep' | grep -c '/usr/bin/serverchan/serverchan'`

两个命令，都是返回0
![image](https://user-images.githubusercontent.com/77531918/112563085-a04f3380-8e13-11eb-86f6-a724f03cf36d.png)

**Comment by kailiu42** [comment]
> 运行 `ps|grep -v grep|grep -c serverchan`
> 查看返回数据
> 这个命令存在于
> /usr/lib/lua/luci/controller/serverchan.lua 文件

因为有些固件内用的`ps`来自于`busybox`，有些来自于`procps-ng-ps`。前者不带参数默认输出所有进程，后者需要带`-A/-e/a`等参数才会输出所有进程。使用后者的固件于是错误的认为serverchan进程没有在运行。只需要修改`serverchan.lua`文件将`ps`命令改为`busybox ps`即可。使用`busybox ps`命令在前者上也是可用的，因此建议作者在代码里面统一修改。

**Comment by mikeinblue** [comment]
> > 你试试
> > `top -bn1 | grep -v 'grep' | grep -c '/usr/bin/serverchan/serverchan'`
> 
> 两个命令，都是返回0
> ![image](https://user-images.githubusercontent.com/77531918/112563085-a04f3380-8e13-11eb-86f6-a724f03cf36d.png)

你搞定了吗？

**Comment by magihub** [comment]
没有！后来不搞了
 
发件人： mikeinblue
发送时间： 2021-04-26 12:57
收件人： tty228/luci-app-serverchan
抄送： magihub; Mention
主题： Re: [tty228/luci-app-serverchan] 怎么老是显示红色的“serverchan NOT RUNNING”呢 (#130)
你试试
top -bn1 | grep -v 'grep' | grep -c '/usr/bin/serverchan/serverchan'
两个命令，都是返回0
你搞定了吗？

**Comment by mikeinblue** [comment]
> 没有！后来不搞了 发件人： mikeinblue 发送时间： 2021-04-26 12:57 收件人： tty228/luci-app-serverchan 抄送： magihub; Mention 主题： Re: [tty228/luci-app-serverchan] 怎么老是显示红色的“serverchan NOT RUNNING”呢 (#130) 你试试 top -bn1 | grep -v 'grep' | grep -c '/usr/bin/serverchan/serverchan' 两个命令，都是返回0 你搞定了吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我记得以前天灵固件是有微信推送的，为什么现在都没有了
