### ISSUE TITLE
运行报错 sh: out of range

### ISSUE THREAD

**Issue by Dellear** [tty228/luci-app-serverchan#131]
今天升级了最新的1.82后，就连续报错 sh: out of range，手动执行send也会报错。但是消息可以正常推送。
![image](https://user-images.githubusercontent.com/22325851/111907721-9040f800-8a91-11eb-8e70-9879b257ae3a.png)

**Comment by tty228** [comment]
我这边正常
可能是 sh 版本不一样，某些语法不支持
尝试使用 sh -x  获取详细运行信息

**Comment by Dellear** [comment]
> 我这边正常
> 可能是 sh 版本不一样，某些语法不支持
> 尝试使用 sh -x 获取详细运行信息

是这样的，应该是直接调用的ash
![image](https://user-images.githubusercontent.com/22325851/112123419-36107600-8bfc-11eb-9cf7-aa0a892ecc48.png)

**Comment by tty228** [comment]
`sh -x  /usr/bin/serverchan/serverchan send`

**Comment by Dellear** [comment]
> `sh -x /usr/bin/serverchan/serverchan send`

日志已抓取，请大佬看看

[send.log](https://github.com/tty228/luci-app-serverchan/files/6202106/send.log)
