### ISSUE TITLE
请教，尝试添加pushplus推送，编译成功，安装成功，进入配置时报错，报错信息如下

### ISSUE THREAD

**Issue by LeanFly** [tty228/luci-app-serverchan#132]
500 内部服务器错误
对不起，服务器遇到未知错误。

/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/admin/services/serverchan'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/serverchan/setting'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:74: Failed to load template 'serverchan/status'.
Error while parsing template '/usr/lib/lua/luci/view/serverchan/status.htm':
Syntax error in /usr/lib/lua/luci/view/serverchan/status.htm:1: unfinished string near '"

**添加代码如下**
_**luasrc/model/cbi/serverchan/setting.lua**_
在
```
a=s:taboption("basic", Value,"chat_id",translate('TG_chatid'),translate("").."获取 chat_id <a href='https://t.me/getuserIDbot' target='_blank'>点击这里</a>")

a.rmempty = true
```
后添加
```
a=s:taboption("basic",Value,"pushplus_token",translate('pushplus_token'),translate("").."获取pushplus_token <a href='http://www.pushplus.plus/' target='_blank'>点击这里</a><br>")
a.rmempty = true
```

_**root/usr/bin/serverchan/serverchan**_
在921行
`	[ "$send_disturb" -eq "0" ] && [ ! -z "$tg_token" ] && curl -s "https://api.telegram.org/bot${tg_token}/sendMessage" -d "chat_id=${chat_id}&text=${send_title}${nowtime}${send_content}" >/dev/null 2>&1`
后添加
`	[ "$send_disturb" -eq "0" ] && [ ! -z "$pushplus_token" ] && curl -s "http://pushplus.plus/send?token=${pushplus_token}" -d "&title=${send_title}&content=${nowtime}${markdown_linefeed}${send_content}" >/dev/null 2>&1
`
在996行后添加
`	[ "$send_disturb" -eq "0" ] && [ ! -z "$pushplus_token" ] && curl -s "http://pushplus.plus/send?token=${pushplus_token}" -d "&title=${send_title}&content=${nowtime}${markdown_linefeed}${send_content}" >/dev/null 2>&1
`

**Comment by tty228** [comment]
需要修改的地方：
/usr/lib/lua/luci/model/cbi/serverchan
（这里没有问题，可能你换行符或者编码错误，用 WINSCP 内置编辑器保存试试，或者卸载重新修改，可能改到了其他文件）

root/usr/bin/serverchan/serverchan
第13行添加
`"pushplus_token"` 变量，读取配置文件中的 pushplus_token 参数

在922行后添加（定时推送）添加 `&template=markdown` 支持 markdown 语法
[ "$send_disturb" -eq "0" ] && [ ! -z "$pushplus_token" ] && curl -s "http://pushplus.plus/send?token=${pushplus_token}" -d "&title=${send_title}&content=${nowtime}${markdown_linefeed}${send_content}**&template=markdown**" >/dev/null 2>&1

在996行后添加(状态推送)
[ "$disturb" -eq "0" ] && [ ! -z "$pushplus_token" ] && curl -s "http://pushplus.plus/send?token=${pushplus_token}" -d "&title=${title}&content=${nowtime}${markdown_linefeed}${content}&template=markdown" >/dev/null 2>&1

不过我试了一下，换行符有点问题，还需要把变量 `markdown_tab` 清空
27行
`markdown_tab="     "` 改为 `markdown_tab=""`

**Comment by LeanFly** [comment]
多谢大佬指导，之前是在win环境用的vscode修改的代码。换到了Ubuntu下调整后编译成功运行，pushplus推送成功
