### ISSUE TITLE
微信推送读取不了cpu温度

### ISSUE THREAD

**Issue by aachuanga** [tty228/luci-app-serverchan#134]
![image](https://user-images.githubusercontent.com/41410139/112745177-14870400-8fd9-11eb-90d7-42257b18d43b.png)
TTYD 终端用c| grep -E 'temp1|temp2|Package|Core' | sed 's/temp2/<br>temp2/g'和sensors  可以读取cpu温度
微信推送读取不了cpu温度
![image](https://user-images.githubusercontent.com/41410139/112745253-970fc380-8fd9-11eb-9916-f6b88909a8a3.png)
![image](https://user-images.githubusercontent.com/41410139/112745261-a262ef00-8fd9-11eb-86b5-81ce90dd384b.png)
![image](https://user-images.githubusercontent.com/41410139/112745273-aa229380-8fd9-11eb-9b7b-21845a64c076.png)
![image](https://user-images.githubusercontent.com/41410139/112745286-c1618100-8fd9-11eb-8df8-139cc37053b2.png)

**Comment by tty228** [comment]
参考 https://github.com/tty228/luci-app-serverchan/issues/59

**Comment by aachuanga** [comment]
> 参考[＃59](https://github.com/tty228/luci-app-serverchan/issues/59)

![image](https://user-images.githubusercontent.com/41410139/113964934-12396b00-985f-11eb-89e8-caa2c255db41.png)

用   sensors | tail -n +7 | grep "°C" | awk '{print $2}' | sed $'s/+//g' | sed $'s/°C//g'    
感谢大佬解惑 ，我用的是星际宝盒cm520  得加多tail -n +7 这条语句才能获取到单个温度，如果直接用您的语句获取到的是两个温度。

**Comment by tty228** [comment]
建议使用 sensors|grep "°C" | awk '{print $2}' | sed $'s/+//g' | sed $'s/°C//g'|sort -nr|head -n1"
获取最大温度
你那个是指定了特定核心（第7行返回值）

顺便测试这个指令是否正常 
`sensors|grep °C|sed -nr 's#^.*:.*\+(.*)°C .*#\1#gp'|sort -nr|head -n1`

**Comment by aachuanga** [comment]
![image](https://user-images.githubusercontent.com/41410139/114299537-660db380-9aee-11eb-8259-86ae7dc51794.png)


> 建议使用 sensors|grep "°C" | awk '{print $2}' | sed $'s/+//g' | sed $'s/°C//g'|sort -nr|head -n1"
> 获取最大温度
> 你那个是指定了特定核心（第7行返回值）
> 
> 顺便测试这个指令是否正常
> `sensors|grep °C|sed -nr 's#^.*:.*\+(.*)°C .*#\1#gp'|sort -nr|head -n1`

**Comment by aachuanga** [comment]
> 建议使用 sensors|grep "°C" | awk '{print $2}' | sed $'s/+//g' | sed $'s/°C//g'|sort -nr|head -n1"
> 获取最大温度
> 你那个是指定了特定核心（第7行返回值）
> 
> 顺便测试这个指令是否正常
> `sensors|grep °C|sed -nr 's#^.*:.*\+(.*)°C .*#\1#gp'|sort -nr|head -n1`
![image](https://user-images.githubusercontent.com/41410139/114299574-aa00b880-9aee-11eb-8689-d3dbd32efc77.png)
![image](https://user-images.githubusercontent.com/41410139/114299595-c7ce1d80-9aee-11eb-885f-194a8c86d0d3.png)
![image](https://user-images.githubusercontent.com/41410139/114299624-eb916380-9aee-11eb-96fe-ce2d2e594783.png)

这两个指令都可以用，感谢大佬分享！
server酱准备关闭公众号推送了，准备启用企业微信通道，我看了一下，企业微信推送好像还蛮简单的，但是我不懂openwrt插件开发。大佬后续会出企业微信推送吗？

**Comment by tty228** [comment]
直接填入 SendKey 即可，新旧通用
