### ISSUE TITLE
自己搭的telechan能用上嘛？

### ISSUE THREAD

**Issue by zcluo** [tty228/luci-app-serverchan#135]
是不是只要修改下发消息的网址？能指导下在哪个文件改？

**Comment by tty228** [comment]
参考这个
https://github.com/tty228/luci-app-serverchan/issues/132

**Comment by tty228** [comment]
或者你试试1.80版本，参考这个，应该不用修改源码就能用

**Comment by zcluo** [comment]
好的谢谢大佬
