### ISSUE TITLE
Server酱升级Turbo版了。

### ISSUE THREAD

**Issue by ccbcfan** [tty228/luci-app-serverchan#136]
luci-app-serverchan 能支持新版了吗？

**Comment by easychen** [comment]
> luci-app-serverchan 能支持新版了吗？

最新的代码应该是支持了 Turbo 的  → https://github.com/tty228/luci-app-serverchan/blob/83ba1c468a665272b11c86031588a13f51735867/root/usr/bin/serverchan/serverchan#L29
