### ISSUE TITLE
[bug]有关pushplus推送

### ISSUE THREAD

**Issue by Qliangw** [tty228/luci-app-serverchan#138]
push+原api已经更换
需要替换为最新的[http://pushplus.hxtrip.com/send](url)
且最新好像不支持md格式了，显示默认为html。

但希望作者能更新api接口，优化显示内容。

**Comment by xylz0928** [comment]
你这个不是pushplus官网，参见pushplus.plus

**Comment by Qliangw** [comment]
> 你这个不是pushplus官网，参见pushplus.plus

ok ok，我这个原来是老的推送地址
