### ISSUE TITLE
iOS或所有苹果设备下线通知不正常

### ISSUE THREAD

**Issue by ZeaKyX** [tty228/luci-app-serverchan#14]
检查设备在线情况的ping和arping对苹果设备（实测iPhone iOS12，大概率全部类似）无效，手机锁屏后大约2秒就ping不通了，也就导致出现设备离线误判。实测亮屏或者锁屏有后台数据运行时可ping通。

**Comment by tty228** [comment]
arping 失效的话，大概就没办法了……就是为了避免休眠设备的检测才使用的 arping 
印象里之前手上的 iPhone6 是没问题的，系统没记错就是 ios12
可能是更新了什么内容吧
你试试使用ssh工具，再手动 arping 看看结果，我怀疑 arping 命令没有正常运行

**Comment by tty228** [comment]
arping 命令格式
arping -I wlan0 -c 10 -f -w 3 192.168.3.86
arping -I br-lan -c 10 -f -w 3 192.168.1.86


ip=192.168.3.86
arping -I $( cat /proc/net/arp | grep -w $ip | awk  '{print $6}' | grep -v "^$" | sort -u ) -c 10 -f -w 3 $ip

你在点亮屏幕的时候测试一下能不能ping通，如果不能说明没有正常运行，如果可以的话……
那只能找其他检测休眠设备的方法了

**Comment by ZeaKyX** [comment]
> arping 命令格式
> arping -I wlan0 -c 10 -f -w 3 192.168.3.xx
> arping -I br-lan -c 10 -f -w 3 192.168.1.xx
> 
> 脚本中语句：
> ip=192.168.xx.xx
> arping -I $( cat /proc/net/arp | grep -w $ip | awk '{print $6}' | grep -v "^$" | sort -u ) -c 10 -f -w 3 $ip
> 
> 你在点亮屏幕的时候测试一下有没有出错，如果可以的话……
> 那只能找其他检测休眠设备的方法了


> arping 命令格式
> arping -I wlan0 -c 10 -f -w 3 192.168.3.xx
> arping -I br-lan -c 10 -f -w 3 192.168.1.xx
> 
> 脚本中语句：
> ip=192.168.xx.xx
> arping -I $( cat /proc/net/arp | grep -w $ip | awk '{print $6}' | grep -v "^$" | sort -u ) -c 10 -f -w 3 $ip
> 
> 你在点亮屏幕的时候测试一下有没有出错，如果可以的话……
> 那只能找其他检测休眠设备的方法了

> 

> arping 命令格式
> arping -I wlan0 -c 10 -f -w 3 192.168.3.xx
> arping -I br-lan -c 10 -f -w 3 192.168.1.xx
> 
> 脚本中语句：
> ip=192.168.xx.xx
> arping -I $( cat /proc/net/arp | grep -w $ip | awk '{print $6}' | grep -v "^$" | sort -u ) -c 10 -f -w 3 $ip
> 
> 你在点亮屏幕的时候测试一下有没有出错，如果可以的话……
> 那只能找其他检测休眠设备的方法了

`root@OpenWrt:~# arping -I br-lan -c 10 -f -w 3 192.168.2.100
ARPING 192.168.2.100 from 192.168.2.1 br-lan
Unicast reply from 192.168.2.100 [xxxxxxxxx]  104.742ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
root@OpenWrt:~# arping -I br-lan -c 10 -f -w 3 192.168.2.100
ARPING 192.168.2.100 from 192.168.2.1 br-lan
Sent 4 probes (4 broadcast(s))
Received 0 response(s)
`
仍然是同样结果，上面是亮屏，下面锁屏2秒后。（不过查看arp表为什么接口不是wlan呢？）
同时测试锁屏的Android 9.0可ping通
可惜其他苹果设备不在身边，也没有更新ios13，不能测试
不过openwrt检查在线的方法都快用尽了，实在为难人

**Comment by ZeaKyX** [comment]
> arping 失效的话，大概就没办法了……就是为了避免休眠设备的检测才使用的 arping
> 印象里之前手上的 iPhone6 是没问题的，系统没记错就是 ios12
> 可能是更新了什么内容吧
> 你试试使用ssh工具，再手动 arping 看看结果，我怀疑 arping 命令没有正常运行

另外非常感谢大佬，程序一个多月跑下来十分稳定好用
（除了负载超过的提醒好像没有发出去，虽然日志存在）
再提几个建议加入的功能，希望大佬抽空能实现

1. 微信推送添加自定义标题，对于有多台路由的人好分辨
2.有客户端远程登陆web和连接ssh的提醒

**Comment by tty228** [comment]
IOS12.1.4正常

**Comment by ZeaKyX** [comment]
> IOS12.1.4正常

进一步测试后发现灭屏后第一次ping大概率ping不通，但是持续ping后就经常会有发出4个探针然后接受到一个的情况，设备ip7，8，ios12.4 ios13.1.2 ios13.2.2都有

**Comment by tty228** [comment]
那你把检测超时时间改一下吧

**Comment by tty228** [comment]
不知道基于系统日志读取到的会不会精准一点
