### ISSUE TITLE
企业微信推送无效

### ISSUE THREAD

**Issue by ghost** [tty228/luci-app-serverchan#145]
已经按规定设置好
`a8*******d8378;c****a;100000*;J*******SL354mad********SFqfo`

但是没有任何反应

**Comment by notfound945** [comment]
附议，我也是这种情况

**Comment by shuosiw** [comment]
自行编译的版本么？我本地自测是 OK 的，详细信息参考这个 PR 的介绍：https://github.com/tty228/luci-app-serverchan/pull/144

另外，最好提供一下更详细的点的信息，日志、截图什么的，方便定位问题

**Comment by tofuliang** [comment]
我调试了下，资源不能跨账号使用？
```javascript

{"errcode":40007,"errmsg":"invalid media_id, hint: [1626087030_150_91501fc7caab284d4971989b79da8f9c], from ip: 59.42.43.246, more info at https://open.work.weixin.qq.com/devtool/query?e=40007"}

```

**Comment by shuosiw** [comment]
看起来确实是这个问题，那么现在就不太好搞了：

1. 使用 mpnews 类型的信息，是必须要设置 media_id（见[图文消息（mpnews）](https://work.weixin.qq.com/api/doc/90000/90135/90236#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89)）
2. 但是这个 media 不能共享，就相当于每个应用都需要自己去上传，这个成本太高了
3. 让 luci-app-serverchan 来提供这个上传操作获取 media_id 感觉也不太现实

如果是把这 media_id 暴露参数给用户的话，可以解决问题，但就是加大了用户成本

---

如果是降级到 news 图文消息，是可以使用外部 url，不过

1. 推送的信息不回存在的微信服务器，但我们又没有完整的服务来保存消息，所以只能看到卡片，没法打开链接
2. 卡片展示的信息，长度有限

**Comment by tofuliang** [comment]
> 如果是把这 media_id 暴露参数给用户的话，可以解决问题，但就是加大了用户成本

我觉得用户自行解决media_id好了，毕竟都能解决各个id,secret了，多搞个media_id不算什么，教程到处都是。

**Comment by notfound945** [comment]
我自己研究了下脚本代码，目前仅采用 企业微信推送 Markdown 消息 这种方案。
得益于大佬的脚本代码灵活性高，可以轻松替换相关H5标签至Markdown语法。
目前使用感觉很好，感谢大佬！

Tips: 不过有个问题，系统运行状态不能获取到内外网IP地址、设备总计流量统计不正确，这让我感到疑惑。

**Comment by shuosiw** [comment]
之前也有考虑过 markdown 类型消息，但是 markdown 消息只能在 企业微信 app 里面查看..而我不需要安装企业微信，最终选择了 mpnews 类型。

> Tips: 不过有个问题，系统运行状态不能获取到内外网IP地址、设备总计流量统计不正确，这让我感到疑惑。
这个应该是脚本其他适配的问题了，我路由器是 k3，能正常获取到。

**Comment by rq1025330** [comment]
> 已经按规定设置好
> `a8*******d8378;c****a;100000*;J*******SL354mad********SFqfo`
> 
> 但是没有任何反应

解决了吗

**Comment by tofuliang** [comment]
临时解决方法：自己上传图片，取得media_id后，替换掉 `/usr/bin/serverchan/serverchan` 的69行中的`thumb_media_id`内容。
或者等@shuosiw 再pr吧。

**Comment by shuosiw** [comment]
@tofuliang @rq1025330 @notfound945 @binsee 已经提交 pr 了，可以自行测试：https://github.com/tty228/luci-app-serverchan/pull/149

**Comment by tofuliang** [comment]
不知道大家有没有遇到，新设备上线的时候，是不是HTML标签被转义了？


![mmexport1626709969363](https://user-images.githubusercontent.com/1814685/126189631-28a09224-8abc-406c-ab73-3eb024f15265.jpg)

**Comment by shuosiw** [comment]
我用 mpnews 没有这个问题，估计你这种需要使用 digest 的那个变量，也就是不需要 html 格式

![](https://user-images.githubusercontent.com/2578976/122791067-778fea80-d2eb-11eb-87be-498f973aac71.png)

**Comment by notfound945** [comment]
> @tofuliang @rq1025330 @notfound945 @binsee 已经提交 pr 了，可以自行测试：#149

测试完成！测试环境 Exsi + eSir，
