### ISSUE TITLE
Openwrt 版本  请问不知道怎么能测试一下推送？

### ISSUE THREAD

**Issue by nierde111** [tty228/luci-app-serverchan#150]
Openwrt 版本  请问不知道怎么能测试一下推送？  找了半天没有这个功能。
我也是openwrt r21 x86 版本  安装的时候也是报错了 但是莫名其妙的 服务里面又出现了这个程序  并且看起来能正常运行 就很有意思，但是我还是没弄清楚怎么能推送测试。

 之前用梅林的时候，真的感觉非常好用！ 我是直接把我梅林设备上的SCKEY 复制到了openwrt上 应该是ok的吧我觉得
非常感谢您的work！

**Comment by shuosiw** [comment]
@nierde111 开个命令行终端，执行：

```
/usr/bin/serverchan/serverchan send
```

**Comment by nierde111** [comment]
> @nierde111 开个命令行终端，执行：
> 
> ```
> /usr/bin/serverchan/serverchan send
> ```

好的谢谢了
