### ISSUE TITLE
我企业微信推送失败，你们有推送成功的么

### ISSUE THREAD

**Issue by nj123456** [tty228/luci-app-serverchan#151]
corpid;userid;agentid;corpsecret

corpsecret就是“应用”的secret，是不是

**Comment by Dellear** [comment]
应该是的，我企业微信推送也失败

**Comment by Dellear** [comment]
安装1.8.6版本可以了，需要media_id

**Comment by shuosiw** [comment]
> corpid;userid;agentid;corpsecret
> 
> corpsecret就是“应用”的secret，是不是

有更新了，需要总共需要设置 5 个字段，最后一个是 media_id

**Comment by tty228** [comment]
文档说明好像 media_id 有效期只有三天？

**Comment by shuosiw** [comment]
> 文档说明上好像说 media_id 有效期只有三天？
> 之前没用过企业微信，干脆做成动态获取 media_id 了

我已经用了一个多月了，media_id 还是照常用，没过期

**Comment by tty228** [comment]
行吧，了解了
