### ISSUE TITLE
安装成功后无法启动

### ISSUE THREAD

**Issue by coalzhao** [tty228/luci-app-serverchan#153]
opkg安装,显示is starting now...但是进入到web页面查看发现服务并为启动,勾选启用,配置key全ok,保存设置后仍显示未运行

**Comment by tty228** [comment]
提交bug时请尽量带上设备信息，日志与描述 （如执行 /usr/bin/serverchan/serverchan 后的提示、日志信息、/tmp/serverchan/ipAddress 文件信息、或尝试使用 sh -x /usr/bin/serverchan/serverchan 查看详细运行信息 ）
