### ISSUE TITLE
请问如何停止server酱turbo版的网页版推送？

### ISSUE THREAD

**Issue by liyuhaolol** [tty228/luci-app-serverchan#154]
我在Server酱Turbo版注册以后，填入了企业微信信息。然后软路由也填入了企业微信信息，从那以后，每次推送都是2条，我把网页改成方糖服务号的话，每次推送又会推到企业微信1条，方糖服务号1条，根本无法关掉网页推送啊~请问如何操作呢？

**Comment by shuosiw** [comment]
@liyuhaolol 这里面有两种企业微信推送：

1. 通过 server 酱提供的企业微信推送，也就是信息路径是：路由 -> server酱 -> 企业微信推送接口 -> 你的手机
2. 直接利用 serverchan 提供的企业微信推送，路径是：路由 -> 企业微信推送接口 -> 你的手机

需要先弄清楚是哪一种，如果是第一种，记得 serverchan 页面上的企业微信凭证不要填。

**Comment by liyuhaolol** [comment]
> @liyuhaolol 这里面有两种企业微信推送：
> 
> 1. 通过 server 酱提供的企业微信推送，也就是信息路径是：路由 -> server酱 -> 企业微信推送接口 -> 你的手机
> 2. 直接利用 serverchan 提供的企业微信推送，路径是：路由 -> 企业微信推送接口 -> 你的手机
> 
> 需要先弄清楚是哪一种，如果是第一种，记得 serverchan 页面上的企业微信凭证不要填。

一旦填写已经不能取消了，我现在选择自定义模式，随便填了一个没用的json

**Comment by shuosiw** [comment]
没有用 server 酱 turbo 版，不清楚怎么设置。

PS：如果你都要用企业微信了，完全可以考虑抛弃 server 酱

**Comment by tty228** [comment]
是不是企业微信和 sckey 都填上了

**Comment by liyuhaolol** [comment]
> 是不是企业微信和 sckey 都填上了

您这么一说，突然就豁然开朗了，等于如果我使用您推荐的企业微信推送，其实sckey不是必填项了，我只需要填写企业微信信息就好了，我以为还以为跟老版本一样，sckey属于必填项呢，哈哈，晚上回去删了去。

**Comment by shuosiw** [comment]
我记得，如果你没付费的话，serverchan 的企业微信推送，每天也只能免费 5 条..所以才搞了企业微信推送 haha，随便推
