### ISSUE TITLE
不知道是不是我的问题，定时发送不生效，而且计划任务会消失不见

### ISSUE THREAD

**Issue by Deleted-Account** [tty228/luci-app-serverchan#161]
x86软路由半年没升级，看了下 serverChan 有更新，就更新了个最新版

以前是在计划任务有类似
0 9 * * * /usr/bin/serverchan/serverchan send &
这样进行发送，现在是取消计划任务了吗？

网页上serverChan保存并应用之后，
计划任务那条serverChan会消失，
之后也没法按照计划收到推送（手动推送已测试没有问题）

还是说我需要先重置serverChan的配置？（是否需要？需要的话如何重置？）

但是我另一台路由，刷了自己编译进去的固件，新的serverChan也是这个问题（隔壁的pushbot也一样，计划任务会消失）

ps. 自己加入计划任务是可以定时推送的，但是执行一次 /usr/bin/serverchan/serverchan send 后，
那条包含 /usr/bin/serverchan/serverchan send 的计划任务，会被删除
(目前只能另外写一个脚本执行 /usr/bin/serverchan/serverchan send 来规避删除了)

**Comment by Deleted-Account** [comment]
我另外个路由，编译的最新serverChan，又没有以上问题了

不知道是不是动到什么，比如装了pushbot又卸载或者其他什么的，这个issue我还是关闭吧

**Comment by qin9125** [comment]
最后怎么解决的？我的也是定时推送不起作用，点手动也不行
