### ISSUE TITLE
变量冒到引号外面了

### ISSUE THREAD

**Issue by xylz0928** [tty228/luci-app-serverchan#163]
https://github.com/tty228/luci-app-serverchan/blob/7fc855f2618a6ad122d8c1add9bf72ad1cd12ad9/root/usr/bin/serverchan/serverchan#L721
https://github.com/tty228/luci-app-serverchan/blob/7fc855f2618a6ad122d8c1add9bf72ad1cd12ad9/root/usr/bin/serverchan/serverchan#L1107
下次更新顺便改下哦？

**Comment by tty228** [comment]
OK
