### ISSUE TITLE
web&ssh登录信息推送在ipv6下测试反馈

### ISSUE THREAD

**Issue by ghost** [tty228/luci-app-serverchan#164]
目前在外网环境下使用ipv6公网地址，uhttpd监听ipv6地址web使用自定义端口，Dropbear开启ssh自定义端口。web使用ipv6公网地址ssl证书登录， ssh使用密码公钥登录。确认web&ssh登录成功。无检测到web和ssh登录信息，检查系统日志有登录信息记录，程序没有推送消息。
个人觉得:是否能在serverchan设置界面添加自定义httpd监听web&ssh端口来达到检测目的?包括ipv4地址及ipv6地址(http和https访问)。可行？

**Comment by tty228** [comment]
962行
`cat ${dir}login_monitor|grep -i "accepted login"|awk '{print $4" "$NF}' >> ${dir}web_login
	cat ${dir}login_monitor|grep -i "Password auth succeeded\|Pubkey auth succeeded"|awk '{print $4" "$NF" "$8}' >> ${dir}ssh_login
	cat ${dir}login_monitor|grep -i "failed login"|awk '{print $NF}' >> ${dir}web_failed
	cat ${dir}login_monitor|grep -i "Bad password attempt\|Login attempt for nonexistent user from"|awk '{print $NF}' >> ${dir}ssh_failed`

**Comment by yin666666** [comment]
看来ipv6还不是很普及，我这是移动大内网，只有ipv6有公网IP，……

**Comment by CHNTDCS** [comment]
我路由器也开了ipv6了，外网web登录（ddns+https）没有提示，ssh用key登录是有提示的。

**Comment by tty228** [comment]
我这边比较奇葩，没转公网之前就没有 ipv6 ，大概是桥接的时候师傅没关掉光猫的 DHCPv6，不过没太关注

**Comment by 82kg** [comment]
为啥我的x86 的系统日志 不记录任何 web登录的日志

**Comment by yin666666** [comment]
> 我这边比较奇葩，没转公网之前就没有 ipv6 ，大概是桥接的时候师傅没关掉光猫的 DHCPv6，不过没太关注

用超级密码进光猫后台看看，是否开启ipv4和ipv6双栈协议，选择桥接路由器模式

**Comment by tty228** [comment]
已添加 IPv6 支持
