### ISSUE TITLE
测试发送和手动发送收不到。

### ISSUE THREAD

**Issue by Jokerestelle** [tty228/luci-app-serverchan#174]
token和chat_id填写的没有问题，软件日志显示发送成功，但是telegram收不到信息。
![D56B1935-9276-4AA0-901A-7DE9F167A465](https://user-images.githubusercontent.com/92315971/139889998-440ff983-8176-42d5-bb1b-9e421510b28f.png)
![1A79EDB3-CF4F-4491-B951-CCB8178A8F53](https://user-images.githubusercontent.com/92315971/139890043-2d633018-5762-4374-b991-2970f873b0e9.png)

**Comment by Kaiyuan** [comment]
怎么解决？
