### ISSUE TITLE
【！！！】json 文件生成失败，请检查文件格式

### ISSUE THREAD

**Issue by thz-hub** [tty228/luci-app-serverchan#176]
【！！！】json 文件生成失败，请检查文件格式这是怎么回事

**Comment by dh53128** [comment]
opkg remove luci-app-serverchan
rm -rf /etc/config/serverchan

**Comment by yuan6975** [comment]
我遇到过这个问题  依赖什么都是有安装的    最后发现是/usr/bin/jq 这个依赖文件空白  卸载重新安装jq依赖正常了
