### ISSUE TITLE
无法获取PVE温度

### ISSUE THREAD

**Issue by 596142041** [tty228/luci-app-serverchan#179]
通过ssh登录可以获取温度
![image](https://user-images.githubusercontent.com/4958182/142738021-c8dc4b7c-64a0-4d25-9583-fb5f1cf58228.png)
但是在网页里面无法获取,输出为空
![image](https://user-images.githubusercontent.com/4958182/142738043-c9e2d8f0-5708-4755-92c5-bfca207afeca.png)

这是什么原因啊

**Comment by haohao232323** [comment]
我的倒是可以获取，但是获取到的温度应该是系统温度100摄氏度以上，并不是CPU的温度，现在也没找到解决的办法
