### ISSUE TITLE
开启openclash之后发送不了信息

### ISSUE THREAD

**Issue by FrankYip1020** [tty228/luci-app-serverchan#180]
开启openclash telegram微信都收不了信息，用passwall则正常

**Comment by MBRjun** [comment]
OpenClash 的相关信息 和 log 方便贴下吗？

**Comment by mowdy** [comment]
我的是因为https://github.com/tty228/luci-app-serverchan/issues/176里提到的jq问题导致的，按其说明重装jq后解决。
root@bigbiguniverse:~# ll /usr/bin/jq
-rwxr-xr-x    1 root     root             0 Mar 24 02:16 /usr/bin/jq*
root@bigbiguniverse:~# opkg remove jq --force-depends
Removing package jq from root...
root@bigbiguniverse:~# opkg install jq
Installing jq (1.6-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.3/packages/aarch64_cortex-a53/packages/jq_1.6-1_aarch64_cortex-a53.ipk
Configuring jq.
root@bigbiguniverse:~# ll /usr/bin/jq
-rwxr-xr-x    1 root     root        245827 Feb 11  2019 /usr/bin/jq*
root@bigbiguniverse:~# /etc/init.d/serverchan start
serverchan is starting now ...
root@bigbiguniverse:~#
