### ISSUE TITLE
建议增加一个通过TG机器人发送远程指令控制路由器的功能

### ISSUE THREAD

**Issue by Marionic0723** [tty228/luci-app-serverchan#185]
比如：
输入 **/reboot** 远程重启
**/devices** 显示已连接/在线的设备
**/show ip interface** 手动获取各接口IP信息，最好把PPPOE-WAN口的IPv6也带上。不过tg命令好像不支持空格……

**Comment by ZeaKyX** [comment]
这有点突破本插件的用途了，个人认为可以重新讨论一下使用场景

1. 是否要有控制功能
目前仍然只涉及推送通知

2. 是否要有设备集访问（控制）的功能，插件成为设备管理中心
其实现在用ssh查询pve算是走出了这一步，既然ssh是能接受的方法那应用范围就广了
路由器相信很多人都有多个组mesh了，是不是可以用`iwinfo`统一检测上下线——那就比arping稳多了
甚至比如是不是所有的类Linux设备都可以监控CPU负载、温度等等，直接搞出个AC+AP？

上面这些方案如果能实现，和其他已有方案比较有没有优势？比如[Homeassistant的集成](https://www.home-assistant.io/integrations/ubus/)、恩山各种Openwrt控制App等

当然了，开发这么多功能说说简单，@tty228 大佬就肝了: )

**Comment by tty228** [comment]
这些功能有现成的插件的
https://github.com/alexwbaule/telegramopenwrt
https://github.com/filirnd/Lede_Openwrt_Telegram_Bot

**Comment by tty228** [comment]
> 这有点突破本插件的用途了，个人认为可以重新讨论一下使用场景
> 
> 1. 是否有控制功能
>    目前仍然只涉及通知
> 2. 如果有什么设备设备集访问（控制）的功能，那么插件设备管理
>    现在就用 ssh 查询pve 进行了这一步中心，ssh 是能够接受的那应用范围就广了
>    路由器相信很多人有多个目测了，不是可以用`iwinfo`统一检测上下线——那比arping稳多了，
>    甚至可以说不是所有的类的Linux设备都可以监控、温度等等，直接搞个AC+AP？
> 
> 上面这些方案如果能，和其他前面的方案比较有没有优势？[比如Homeassant的集成](https://www.home-assistant.io/integrations/ubus/)、控制恩山各种OpenwrtApp等
> 
> 开发了这么简单的说法当然了大8 ，@tty222

iw 检测在线的功能有做的，不过很多软路由没有无线， iw 检测不能用，所以还是得靠 ping

然后的确是太肝了，最近加班比较忙，八九点回来只想扣手机→_→

**Comment by ZeaKyX** [comment]
> > 这有点突破本插件的用途了，个人认为可以重新讨论一下使用场景
> > 
> > 1. 是否有控制功能
> >    目前仍然只涉及通知
> > 2. 如果有什么设备设备集访问（控制）的功能，那么插件设备管理
> >    现在就用 ssh 查询pve 进行了这一步中心，ssh 是能够接受的那应用范围就广了
> >    路由器相信很多人有多个目测了，不是可以用`iwinfo`统一检测上下线——那比arping稳多了，
> >    甚至可以说不是所有的类的Linux设备都可以监控、温度等等，直接搞个AC+AP？
> > 
> > 上面这些方案如果能，和其他前面的方案比较有没有优势？[比如Homeassant的集成](https://www.home-assistant.io/integrations/ubus/)、控制恩山各种OpenwrtApp等
> > 开发了这么简单的说法当然了大8 ，@tty222
> 
> iw 检测在线的功能有做的，不过很多软路由没有无线， iw 检测不能用，所以还是得靠 ping
> 
> 然后的确是太肝了，最近加班比较忙，八九点回来只想扣手机→_→

一个逆天想法：软路由ssh到指定的路由器ip集合，再用iwinfo获取列表，统一整理

有线与无线设备列表区分开来，iwinfo得到无线列表的优先级最高，如果iw出现了这个mac地址就加入到无线设备列表，同时删除arp或者其他方法得到的有线列表中的mac地址，以后检查上下线利用已知设备列表就不会混乱了

（摸🐟ing，说话不腰疼😂）
