### ISSUE TITLE
微信突然不推送了，

### ISSUE THREAD

**Issue by lueshuai** [tty228/luci-app-serverchan#187]
但是插件的日志里面看到推送信息流是有的。详细情况我截图
![bc35021530230749467ca7816e9bee5](https://user-images.githubusercontent.com/25924190/147180099-93cbc7a8-4f1a-4978-bc87-ac548477d431.png)
![image](https://user-images.githubusercontent.com/25924190/147180143-b854fc76-41cd-4094-a5d5-4a4973bf8c51.png)
![83cb9cbb77b8d0b4dc08fa3185434ad](https://user-images.githubusercontent.com/25924190/147180431-5c926c57-a53e-4c2a-8f87-aa737cdc0c60.jpg)

**Comment by ReddotCleaner** [comment]
遇到同样问题，20211220之后不推送

**Comment by Dazmk** [comment]
20211220之后不推送 +1

**Comment by ReddotCleaner** [comment]
我的解决了。
说一下我的解决方案：
1.从本项目下载最新安装包安装；
2.执行/usr/bin/serverchan/serverchan，发现缺失jq依赖；
3.安装jq依赖，重置token并重启服务后恢复正常。
 @Dazmk @lueshuai

**Comment by Dazmk** [comment]
> 我的解决了。 说一下我的解决方案： 1.从本项目下载最新安装包安装； 2.执行/usr/bin/serverchan/serverchan，发现缺失jq依赖； 3.安装jq依赖，重置token并重启服务后恢复正常。 @Dazmk @lueshuai

@ReddotCleaner 不好意思刚刚看到，感谢分享，我最近没管这个推送，但是啥也没改动，前两天发现已经恢复正常了。XD

**Comment by Kaiyuan** [comment]
> 我的解决了。 说一下我的解决方案： 1.从本项目下载最新安装包安装； 2.执行/usr/bin/serverchan/serverchan，发现缺失jq依赖； 3.安装jq依赖，重置token并重启服务后恢复正常。 @Dazmk @lueshuai

我安装了 JQ 也是不能推送。
