### ISSUE TITLE
企业微信图文消息提示无法正确获取接口信息,请确认插件是否正常运行

### ISSUE THREAD

**Issue by gongxianhui0** [tty228/luci-app-serverchan#189]
求救，问问这种情况如何处理，不太希望server酱中转，毕竟接口一样的。

**Comment by jxph1123** [comment]
我是直接用的server酱的企业微信程序接口，直接可以的，也没有条数限制，说白了就只是利用了他的应用程序。

**Comment by tty228** [comment]
看看是不是IP获取接口设置错误，wan/lan口这些

**Comment by gongxianhui0** [comment]
并不是这样，server酱正常使用，只是直推微信不行。
