### ISSUE TITLE
自定义推送

### ISSUE THREAD

**Issue by HarryWang29** [tty228/luci-app-serverchan#191]
在openwrt中尝试使用pushdeer接口来对接，结果发现报错如下
>2022-01-27 23:04:02 【！！！】请填写正确的 key 
>2022-01-27 23:04:02 【！！！】读取设置出错，请检查设置项 

于是查看了脚本，发现如下代码
> [ -z "${sckey}${tg_token}${pushplus_token}${corpid}${wxpusher_apptoken}${wxpusher_uids}${wxpusher_topicIds}" ] && echo "`date "+%Y-%m-%d %H:%M:%S"` 【！！！】请填写正确的 key " >> ${logfile} && return 1

可是自定义并不设置这些key啊

**Comment by tty228** [comment]
把 return 1 这一行删掉看看能不能正常运行

**Comment by HarryWang29** [comment]
我后来是把这一整行注释掉了，正常运行了，这两天发现会通知两次，还没看原因
