### ISSUE TITLE
配置页面显示 nplurals=2; plural=(n != 1);

### ISSUE THREAD

**Issue by lyq1996** [tty228/luci-app-serverchan#192]
![捕获](https://user-images.githubusercontent.com/20365480/153202253-707d4539-71b0-4e3b-9374-566d9b58ff63.PNG)

如图所示。

不影响使用，语言设置成英文的话就没有这一串复数规则字符串。

系统是 https://github.com/SuLingGG/OpenWrt-Rpi ，不确定是不是 [setting.lua#L18](https://github.com/tty228/luci-app-serverchan/blob/master/luasrc/model/cbi/serverchan/setting.lua#L18) 的翻译问题。

如果是我个例的话，po主直接关闭issue就好。。

**Comment by tty228** [comment]
大概是，不确定，我一直用的 bootstrap
