### ISSUE TITLE
ipv4 变动不会通知

### ISSUE THREAD

**Issue by mjyhj** [tty228/luci-app-serverchan#195]
看日志基本没有显示ipv4变动，选的是接口pppoe wan

手动重新拨号 日志都没显示的，开了大半年就通知过1，2次

**Comment by tty228** [comment]
二级路由？
获取到的 IP 是什么？
试试改成 URL 获取

**Comment by mjyhj** [comment]
> 二级路由？ 获取到的 IP 是什么？ 试试改成 URL 获取

X86的，主路由。现在换了硬件，不能测了算了
