### ISSUE TITLE
依赖：libwolfssl。若不安装，则推送失败，且没有任何提示。

### ISSUE THREAD

**Issue by chuntsky** [tty228/luci-app-serverchan#199]
建议 注明依赖：libwolfssl。
我的机器此前没有安装 libwolfssl，不能正常发送，还没有任何报错。
在终端手动调用
curl https://sctapi.ftqq.com/xxxxxxxxxxxxxx.send?title=test23&desp=test23messagecontent
提示：
Error loading shared library libwolfssl.so.5.1.1.99a5b54a: No such file or directory (needed by /usr/bin/curl)
**安装libwolfssl 推送正常**。

**Comment by chuntsky** [comment]
> 

有 libopenssl    也可以？

**Comment by tty228** [comment]
我机子也没 libwolfssl ，不过有 libopenssl
