### ISSUE TITLE
貌似脚本有问题

### ISSUE THREAD

**Issue by ZeaKyX** [tty228/luci-app-serverchan#2]
接入设备中有无名设备，系统日志如下重复：
> Mon Jul  8 21:53:05 2019 daemon.err uhttpd[1620]: cut: /sys/class/thermal/thermal_zone0/temp: No such file or directory
> Mon Jul  8 21:53:05 2019 daemon.err uhttpd[1620]: sh: out of range

然后server酱中也有重复日志：

>xxxxxxxxxxx无设备名，尝试重新读取

应该是无设备名有问题

**Comment by tty228** [comment]
这个我有空再看一下，脚本异常退出了吗？
如果没退出的话，大概是空设备名那段代码没做好异常处理

**Comment by ZeaKyX** [comment]
> 这个我有空再看一下，脚本异常退出了吗？
> 如果没退出的话，大概是空设备名那段代码没做好异常处理

后面我查了一下，这个日志上面是检查cpu温度的，这个文件目录不存在……
不知道是否需要安装其他依赖包来检测温度，我用了lmsensor还是没有，手动发送路由状态温度也是空白
不过重启后就没有了这个错误日志，包括下面的无名设备，忽略推送是能正常使用的

**Comment by ZeaKyX** [comment]
> 这个我有空再看一下，脚本异常退出了吗？
> 如果没退出的话，大概是空设备名那段代码没做好异常处理



> 这个我有空再看一下，脚本异常退出了吗？
> 如果没退出的话，大概是空设备名那段代码没做好异常处理

还有一个bug就是手动发送状态后，会自动保存定时发送配置，即便没有点击应用&保存（不设置定时的话没有手动发送按钮）

**Comment by tty228** [comment]
检查cpu温度是基于K3的文件，大概你的设备不一样
无名设备是在因为路由在线设备缓存中，其实此设备以及离线，所以检测不到设备名（但是某些情况下设备依然在线，所以没写成直接跳过）
自动保存是特意设置的，不喜欢可以修改luci
