### ISSUE TITLE
MAC设备信息数据库源网站无法访问了

### ISSUE THREAD

**Issue by xiaotan8** [tty228/luci-app-serverchan#202]
https://linuxnet.ca/ieee/oui.txt  已无法访问，建议改用其它源如  https://standards-oui.ieee.org/oui/oui.txt

查询网址 http://standards-oui.ieee.org/oui.txt 也建议修改为  https://standards-oui.ieee.org/oui/oui.txt 。

**Comment by liujixu1984** [comment]
我试过了把txt下载到本机，然后修改hosts指向本机
