### ISSUE TITLE
在openwrt上运行 识别到设备统计的流量是错误的 ，如何更正

### ISSUE THREAD

**Issue by jk2008chd** [tty228/luci-app-serverchan#204]
![image](https://user-images.githubusercontent.com/69377458/161453470-64745803-c2fb-42ea-a58e-d388a6451f75.png)

**Comment by jk2008chd** [comment]
1. 软件名称：luci-i18n-wrtbwmon-zh-cn

注意：此脚本与SQM QOS、NAT加速等其它nftables类软件有冲突，或导致显示数据不准确等异常。

会不会是因为这个原因？

**Comment by tty228** [comment]
是的
