### ISSUE TITLE
不知道大佬能否把这个插件移植到PVE上

### ISSUE THREAD

**Issue by haohao232323** [tty228/luci-app-serverchan#214]
安装OP使用ssh获取到的温度是系统温度，并不是CPU的温度（经常显示100摄氏度以上），另外主要想监控一下PVE的负载情况和VM的掉线情况

**Comment by 931122** [comment]
修改一下pushbot脚本

**Comment by Marionic0723** [comment]
我也这么想过，但是软路由还是让它老老实实的只负责上网吧，要不然就all in boom了
路由器这玩意最需要的是稳定。
以前折腾过all in one，结果三天两头出问题，而且发热极其严重，我这个又没风扇，最后还是只装路由器系统完事。

**Comment by tty228** [comment]
自行修改一下获取温度的命令行

``[ "$soc_code" == "pve" ] && [ ! -z "$server_host" ] && local soctemp=`ssh -i /root/.ssh/id_rsa root@${server_host} -p ${server_port} sensors 2>/dev/null|grep Core|sed -nr 's#^.*:.*\+(.*)°C .*#\1#gp'|sort -nr|head -n1```
