### ISSUE TITLE
原版openwrt如何安装这个插件

### ISSUE THREAD

**Issue by maxmib** [tty228/luci-app-serverchan#215]
原版openwrt  
固件版本OpenWrt 22.03.0 r19685-512e76967f / LuCI openwrt-22.03 branch git-22.245.77528-487e58a
处理器  mt7620
内核版本5.10.138
下载release里的ipk和通过系统自带软件源安装了iputils-arping ，luci-compat，出现了插件的界面但是启用后界面显示not running，测试功能也不能正常发送消息，ssh登录执行sh /usr/bin/serverchan/serverchan可以运行，且界面显示running，结束命令后
 ps|grep -v grep|grep -c serverchan反馈结果是0，ssh通过curl命令测试可以正常推送消息。

**Comment by tty228** [comment]
提供一下日志信息
看得懂代码的话，运行`sh -x /usr/bin/serverchan/serverchan` 其实就能看出来哪里异常了

然后 jq 装了吗，如果软件源没有这个依赖的话，使用
https://github.com/tty228/luci-app-serverchan/releases/tag/v1.86 版本

**Comment by maxmib** [comment]
jq装了的，sh -x /usr/bin/serverchan/serverchan运行看着没什么报错，手动执行一次代码后luci界面会一直显示running不管界面上选没选启用，测试按钮按个两三次会成功发送消息一次，每次使用测试按钮系统日志里会出现daemon.err uhttpd[1435]: sh: cbi.apply: not found，看起来像是luci 的问题。
这个是日志
[serverchandebug.log](https://github.com/tty228/luci-app-serverchan/files/9709199/serverchandebug.log)

**Comment by maxmib** [comment]
重新编译了原版openwrt 后似乎可以使用了，7621处理器的路由器消息推送比较及时，7620的路由器会间断性不推送，不知道是不是性能问题，切换到18.06再编织个固件试下

**Comment by tty228** [comment]
低性能设备请在高级设置中限制并发线程数
