### ISSUE TITLE
疯狂发送设备登陆信息

### ISSUE THREAD

**Issue by qd201211** [tty228/luci-app-serverchan#22]
疯狂爆设备登陆信息，且每次都是同一些设备。求作者大大快些修复!使用前以对两个serverchan文件给予a+x权限，可以启用，但功能异常。以下是日志：平台x86_64

00:21:20  【清理】日志超出上限，删除前 100 条
00:21:21  【外网IP】正在检测外网IP变化
00:21:21  IP 无变化，当前 ip 为 x.x.x.x
00:21:21 192.168.0.139 24:69:68:5e:c9:e4 无设备名，尝试重新读取
00:21:21  设备 DESKTOP-913I6CS 192.168.0.101 依然坚挺
00:21:21 192.168.0.154 04:cf:8c:50:a9:f6 无设备名，尝试重新读取
00:21:21 192.168.0.2 90:e2:ba:9b:22:52 无设备名，尝试重新读取
00:21:21  设备 debian 192.168.0.165 依然坚挺
00:21:21  设备 未知设备 192.168.0.2 依然坚挺
00:21:21  设备 未知设备 192.168.0.154 依然坚挺
00:21:21  设备 TL-WR842N 192.168.0.104 依然坚挺
00:21:21  设备 Hisense_F26 192.168.0.144 依然坚挺
00:21:21  设备 未知设备 192.168.0.139 依然坚挺
00:21:21  没有检测到设备离线
00:21:21 【等待】我累了，60 秒后再回来
00:22:21  【外网IP】正在检测外网IP变化
00:22:21  IP 无变化，当前 ip 为 x.x.x.x
00:22:21 192.168.0.139 24:69:68:5e:c9:e4 无设备名，尝试重新读取
00:22:21 192.168.0.154 04:cf:8c:50:a9:f6 无设备名，尝试重新读取
00:22:21 192.168.0.2 90:e2:ba:9b:22:52 无设备名，尝试重新读取
00:22:21  设备 DESKTOP-913I6CS 192.168.0.101 依然坚挺
00:22:21  设备 TL-WR842N 192.168.0.104 依然坚挺
00:22:21  设备 debian 192.168.0.165 依然坚挺
00:22:21  设备 未知设备 192.168.0.2 依然坚挺
00:22:21  设备 Hisense_F26 192.168.0.144 依然坚挺
00:22:21  设备 未知设备 192.168.0.154 依然坚挺
00:22:22  设备 未知设备 192.168.0.139 依然坚挺
00:22:22  没有检测到设备离线
00:22:22 【等待】我累了，60 秒后再回来
00:23:22  【外网IP】正在检测外网IP变化
00:23:22  IP 无变化，当前 ip 为 x.x.x.x
00:23:23 192.168.0.139 24:69:68:5e:c9:e4 无设备名，尝试重新读取
00:23:23 192.168.0.154 04:cf:8c:50:a9:f6 无设备名，尝试重新读取
00:23:23  设备 DESKTOP-913I6CS 192.168.0.101 依然坚挺
00:23:23 192.168.0.2 90:e2:ba:9b:22:52 无设备名，尝试重新读取
00:23:23  设备 debian 192.168.0.165 依然坚挺
00:23:23  设备 Hisense_F26 192.168.0.144 依然坚挺
00:23:23  设备 TL-WR842N 192.168.0.104 依然坚挺
00:23:23  设备 未知设备 192.168.0.2 依然坚挺
00:23:23  设备 未知设备 192.168.0.154 依然坚挺
00:23:23  设备 未知设备 192.168.0.139 依然坚挺
00:23:23  没有检测到设备离线

以此无限循环

**Comment by tty228** [comment]
并没有看到推送通知

**Comment by qd201211** [comment]
推送通知如下，内容都是一样的
![7AB18570-00FA-42AC-80D3-ECBD0CEA6953](https://user-images.githubusercontent.com/55730160/70432290-e024c700-1ab9-11ea-8cf6-242cd2cf490f.png)
![179E7D2B-4F0B-4ECE-B406-737F55511CD6](https://user-images.githubusercontent.com/55730160/70432292-e0bd5d80-1ab9-11ea-9d2b-8960026b3bf8.png)
![Uploading CFA1C5A5-EC3B-4FCA-B0A3-3DC6DCF95892.png…]()

**Comment by tty228** [comment]
好歹上传个时间能关联的日志啊，你这样我看不出来东西的

**Comment by qd201211** [comment]
不晓得是不是这个意思，您看下
01:09:19 【初始化】载入配置文件
01:09:19 【初始化】工作目录为 /tmp/serverchan/ 
01:09:19 【初始化】log 目录为 /tmp/serverchan/server_chan.log 
01:09:19 【初始化】未启用 MAC 过滤
01:09:19 【初始化】初始化在线设备列表
01:09:20  新设备 ubuntu 192.168.0.113 连接了
01:09:20  新设备 DESKTOP-RK31P4S 192.168.0.101 连接了
01:09:20  新设备 meilan-Note5 192.168.0.139 连接了
01:09:20  新设备 Hisense_F26 192.168.0.144 连接了
01:09:20  新设备 chuangmi-plug-v3_miio125743711 192.168.0.154 连接了
01:09:20 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
01:09:21 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
01:09:22 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
01:09:23 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
01:09:24 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
01:09:25 获取 192.168.0.2 设备名超时，暂停跳过
01:09:25  新设备 未知设备 192.168.0.2 连接了
01:09:25  新设备 Hello-my-Phone 192.168.0.248 连接了
01:09:42  设备 TL-WR842N 192.168.0.104 连接失败
01:09:42  设备 Tower 192.168.0.143 连接失败
01:09:42  设备 minint-prd1ggq 192.168.0.239 连接失败
01:09:43  【外网IP】正在检测外网IP变化
01:09:43  【微信推送】路由器已经重启!当前IP：x.x.x.x
01:09:43  当前IP: x.x.x.x
01:09:43  设备 DESKTOP-RK31P4S 192.168.0.101 依然坚挺
01:09:43  设备 ubuntu 192.168.0.113 依然坚挺
01:09:44 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
01:09:44  设备 Hisense_F26 192.168.0.144 依然坚挺
01:09:44  设备 meilan-Note5 192.168.0.139 依然坚挺
01:09:44  设备 Hello-my-Phone 192.168.0.248 依然坚挺
01:09:44  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
01:09:44  设备 未知设备 192.168.0.2 依然坚挺
01:09:44  没有检测到设备离线
01:09:44 【连接】开始进行设备接入检测
01:09:44  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
01:09:44 【负载】正在检测 CPU 负载
01:09:44  CPU 负载正常：0.97
01:09:44 【温度】正在检测 CPU 温度
01:09:44  CPU 温度正常：
01:09:45  进行 URL 编码，标题=设备状态变化
01:09:45 【等待】我累了，60 秒后再回来
01:10:46  【外网IP】正在检测外网IP变化
01:10:46  IP 无变化，当前 ip 为 x.x.x.x
01:10:47  设备 DESKTOP-RK31P4S 192.168.0.101 依然坚挺
01:10:47  设备 ubuntu 192.168.0.113 依然坚挺
01:10:47  设备 meilan-Note5 192.168.0.139 依然坚挺
01:10:47 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
01:10:47  设备 Hisense_F26 192.168.0.144 依然坚挺
01:10:47  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
01:10:47  设备  192.168.0.248 依然坚挺
01:10:47  设备 未知设备 192.168.0.2 依然坚挺
01:10:47  没有检测到设备离线
01:10:47 【连接】开始进行设备接入检测
01:10:48  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
01:10:48 【负载】正在检测 CPU 负载
01:10:48  CPU 负载正常：0.67
01:10:48 【温度】正在检测 CPU 温度
01:10:48  CPU 温度正常：
01:10:48  进行 URL 编码，标题=有人连接了你的路由器
01:10:48 【等待】我累了，60 秒后再回来
01:11:50  【外网IP】正在检测外网IP变化
01:11:50  IP 无变化，当前 ip 为 x.x.x.x
01:11:51  设备 DESKTOP-RK31P4S 192.168.0.101 依然坚挺
01:11:51  设备 ubuntu 192.168.0.113 依然坚挺
01:11:51  设备 meilan-Note5 192.168.0.139 依然坚挺
01:11:51 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
01:11:51  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
01:11:51  设备 Hisense_F26 192.168.0.144 依然坚挺
01:11:51  设备  192.168.0.248 依然坚挺
01:11:51  设备 未知设备 192.168.0.2 依然坚挺
01:11:51  没有检测到设备离线
01:11:51 【连接】开始进行设备接入检测
01:11:52  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
01:11:52 【负载】正在检测 CPU 负载
01:11:52  CPU 负载正常：0.80
01:11:52 【温度】正在检测 CPU 温度
01:11:52  CPU 温度正常：
01:11:52  进行 URL 编码，标题=有人连接了你的路由器
01:11:53 【等待】我累了，60 秒后再回来

![BDF3DBA5-05B4-43C6-94B6-AE24AC2BCE26](https://user-images.githubusercontent.com/55730160/70734461-42dec280-1d47-11ea-87a1-a3e745b0cba9.jpeg)
![277125CC-810B-4993-9A3C-EB665F44AD63](https://user-images.githubusercontent.com/55730160/70734462-43775900-1d47-11ea-9c5d-9493e2fdec2f.png)
![2E2A42DE-B1B3-4A68-B127-BDB687D1FA71](https://user-images.githubusercontent.com/55730160/70734464-440fef80-1d47-11ea-8ff5-39e8cbb7aeca.png)

**Comment by tty228** [comment]
有可能 ipAddress 写入的时候，换行格式出错了，你试一下重复发送的时候，打开
/tmp/serverchan/ipAddress 文件看看，复制一下里面的内容，我排查一下

是什么时候编译的？

**Comment by qd201211** [comment]
我第一次发issue是用的x86平台的，这几天发的都是ipq4019的固件（自己编译的用于竞斗云），问题都是一样的。昨天看您更新还没来得及重新编译，现版本是我发布issue时的。以下是日志+ipaddress和推送，谢谢您。

日志
`19:20:23 【初始化】载入配置文件
19:20:23 【初始化】工作目录为 /tmp/serverchan/ 
19:20:23 【初始化】log 目录为 /tmp/serverchan/server_chan.log 
19:20:23 【初始化】未启用 MAC 过滤
19:20:23 【初始化】初始化在线设备列表
19:20:24 获取 192.168.0.101 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:25 获取 192.168.0.101 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:26 获取 192.168.0.101 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:28 获取 192.168.0.101 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:29 获取 192.168.0.101 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:30 获取 192.168.0.101 设备名超时，暂停跳过
19:20:30  新设备 未知设备 192.168.0.101 连接了
19:20:30 获取 192.168.0.144 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:30  新设备 ESP_C7B445 192.168.0.232 连接了
19:20:30  新设备 chuangmi-plug-v3_miio125743711 192.168.0.154 连接了
19:20:30  新设备 Hello-my-Phone 192.168.0.248 连接了
19:20:30  新设备 DESKTOP-74LBDFU 192.168.0.169 连接了
19:20:30  新设备 android-e7ef38dc9031e4a 192.168.0.221 连接了
19:20:30 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:30 获取 192.168.0.102 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:30 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
19:20:31 获取 192.168.0.144 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:31 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:31 获取 192.168.0.102 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:31 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
19:20:32 获取 192.168.0.144 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:32 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:32 获取 192.168.0.102 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:32 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
19:20:33 获取 192.168.0.144 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:34 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:34 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
19:20:34 获取 192.168.0.102 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:34 获取 192.168.0.144 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:35 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:35 获取 192.168.0.2 d0:50:99:5d:0c:9d 设备信息失败，重试中
19:20:35 获取 192.168.0.102 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:35 获取 192.168.0.144 设备名超时，暂停跳过
19:20:35  新设备 未知设备 192.168.0.144 连接了
19:20:36 获取 192.168.0.100 设备名超时，暂停跳过
19:20:36 获取 192.168.0.2 设备名超时，暂停跳过
19:20:36  新设备 未知设备 192.168.0.100 连接了
19:20:36 获取 192.168.0.102 设备名超时，暂停跳过
19:20:36  新设备 未知设备 192.168.0.2 连接了
19:20:36  新设备 未知设备 192.168.0.102 连接了
19:20:36  【外网IP】正在检测外网IP变化
19:20:36  【微信推送】路由器已经重启!当前IP：123.235.239.242
19:20:36  当前IP: 123.235.239.242
19:20:36 192.168.0.100 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:20:37 192.168.0.101 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:20:37 192.168.0.102 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:20:37 192.168.0.144 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:20:37  设备 未知设备 192.168.0.100 依然坚挺
19:20:37  设备 未知设备 192.168.0.101 依然坚挺
19:20:37 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
19:20:37  设备 未知设备 192.168.0.102 依然坚挺
19:20:37  设备 未知设备 192.168.0.144 依然坚挺
19:20:37  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
19:20:37  设备  192.168.0.221 依然坚挺
19:20:37  设备 未知设备 192.168.0.2 依然坚挺
19:20:38  设备  192.168.0.248 依然坚挺
19:20:38  设备  192.168.0.232 依然坚挺
19:20:38  设备 DESKTOP-74LBDFU 192.168.0.169 依然坚挺
19:20:38  没有检测到设备离线
19:20:38 【连接】开始进行设备接入检测
19:20:38  【微信推送】新设备 android-e7ef38dc9031e4a 192.168.0.221 连接了
19:20:38  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
19:20:38  【微信推送】新设备 ESP_C7B445 192.168.0.232 连接了
19:20:39 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:40 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:41 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:42 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:43 获取 192.168.0.100 7e:44:fd:7f:e2:7a 设备信息失败，重试中
19:20:44 获取 192.168.0.100 设备名超时，暂停跳过
19:20:44  【微信推送】新设备 未知设备 192.168.0.100 连接了
19:20:48 【负载】正在检测 CPU 负载
19:20:48  CPU 负载正常：1.83
19:20:48 【温度】正在检测 CPU 温度
19:20:48  CPU 温度正常：
19:20:48  进行 URL 编码，标题=设备状态变化
19:20:48 【等待】我累了，60 秒后再回来
19:21:49  【外网IP】正在检测外网IP变化
19:21:49  IP 无变化，当前 ip 为 123.235.239.242
19:21:50 192.168.0.100 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:21:50 192.168.0.101 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:21:50 192.168.0.102 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:21:50 192.168.0.144 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:21:50  设备 未知设备 192.168.0.101 依然坚挺
19:21:50  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
19:21:50  设备 未知设备 192.168.0.102 依然坚挺
19:21:50 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
19:21:50  设备 未知设备 192.168.0.144 依然坚挺
19:21:50  设备  192.168.0.221 依然坚挺
19:21:50  设备 未知设备 192.168.0.2 依然坚挺
19:21:51  设备  192.168.0.248 依然坚挺
19:21:51  设备 DESKTOP-74LBDFU 192.168.0.169 依然坚挺
19:21:51  设备  192.168.0.232 依然坚挺
19:21:52  设备 未知设备 192.168.0.100 依然坚挺
19:21:52  没有检测到设备离线
19:21:52 【连接】开始进行设备接入检测
19:21:53  【微信推送】新设备 android-e7ef38dc9031e4a 192.168.0.221 连接了
19:21:53  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
19:21:53  【微信推送】新设备 ESP_C7B445 192.168.0.232 连接了
19:22:02 【负载】正在检测 CPU 负载
19:22:02  CPU 负载正常：1.04
19:22:02 【温度】正在检测 CPU 温度
19:22:02  CPU 温度正常：
19:22:02  进行 URL 编码，标题=有人连接了你的路由器
19:22:03 【等待】我累了，60 秒后再回来
19:23:04  【外网IP】正在检测外网IP变化
19:23:04  IP 无变化，当前 ip 为 123.235.239.242
19:23:04 192.168.0.100 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:23:04 192.168.0.101 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:23:04 192.168.0.102 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:23:04 192.168.0.144 7e:44:fd:7f:e2:7a 无设备名，尝试重新读取
19:23:04  设备 未知设备 192.168.0.101 依然坚挺
19:23:05  设备 未知设备 192.168.0.102 依然坚挺
19:23:05  设备 chuangmi-plug-v3_miio125743711 192.168.0.154 依然坚挺
19:23:05 192.168.0.2 d0:50:99:5d:0c:9d 无设备名，尝试重新读取
19:23:05  设备 未知设备 192.168.0.144 依然坚挺
19:23:05  设备 android-e7ef38dc9031e4a 192.168.0.221 依然坚挺
19:23:05  设备 未知设备 192.168.0.2 依然坚挺
19:23:05  设备  192.168.0.248 依然坚挺
19:23:05  设备 DESKTOP-74LBDFU 192.168.0.169 依然坚挺
19:23:05  设备  192.168.0.232 依然坚挺
19:23:05  设备 未知设备 192.168.0.100 依然坚挺
19:23:05  没有检测到设备离线
19:23:05 【连接】开始进行设备接入检测
19:23:06  【微信推送】新设备 android-e7ef38dc9031e4a 192.168.0.221 连接了
19:23:06  【微信推送】新设备 Hello-my-Phone 192.168.0.248 连接了
19:23:06  【微信推送】新设备 ESP_C7B445 192.168.0.232 连接了
19:23:16 【负载】正在检测 CPU 负载
19:23:16  CPU 负载正常：1.26
19:23:16 【温度】正在检测 CPU 温度
19:23:16  CPU 温度正常：
19:23:16  进行 URL 编码，标题=有人连接了你的路由器
19:23:16 【等待】我累了，60 秒后再回来`


ipaddress:

`192.168.0.154 04:cf:8c:50:a9:f6 chuangmi-plug-v3_miio125743711
192.168.0.169 6c:29:95:a5:10:7c DESKTOP-74LBDFU
192.168.0.100 7e:44:fd:7f:e2:7a  |M-* =M-%设 g
192.168.0.101 7e:44:fd:7f:e2:7a  |M-* =M-%设 g
192.168.0.102 7e:44:fd:7f:e2:7a  |M-* =M-%设 g
192.168.0.144 7e:44:fd:7f:e2:7a  |M-* =M-%设 g
192.168.0.2 d0:50:99:5d:0c:9d  |M-* =M-%设 g
192.168.0.221 08:67:4e:7d:07:94 android-e7ef38dc9031e4a
192.168.0.248 54:33:cb:50:66:52 Hello-my-Phone
192.168.0.232 7c:49:eb:c7:b4:45 ESP_C7B445`


推送
![QQ图片20191213194309](https://user-images.githubusercontent.com/55730160/70798052-e7f9a980-1de0-11ea-8ab4-9459737ac7bd.png)
![QQ图片20191213194312](https://user-images.githubusercontent.com/55730160/70798055-eaf49a00-1de0-11ea-84a9-142d1acefeb3.png)
![QQ图片20191213194315](https://user-images.githubusercontent.com/55730160/70798062-f34cd500-1de0-11ea-8893-b9a7ee508f36.png)

**Comment by tty228** [comment]
ipaddress 编码有问题
你先暂时把 serverchan 脚本里面的 “未知设备”全部替换成英文，我有空修复一下

**Comment by qd201211** [comment]
看到您今天更新了！感谢维护！今晚上我开编译看下现在这个版本还有没有问题~

**Comment by whogh** [comment]
每次设备上线下线的时候保留推送mac和ip会好点吧，然后下面隔几行显示当前在线的设备列表
