### ISSUE TITLE
无法获取温度

### ISSUE THREAD

**Issue by qiaoliG** [tty228/luci-app-serverchan#220]
架构	AArch64 Processor : Cortex-A53 * 4
固件版本	OpenWrt R23.04.15 / LuCI Master (git-23.104.57901-bf5e9ad)
内核版本	6.1.26
 
自从更新v2.03.04 及之后版本，默认的获取温度提示 null。
设置自定义温度读取命令后正常： cat /sys/class/thermal/thermal_zone0/temp | awk '{printf("%.1f\n", $1/1000)}'

**Comment by tty228** [comment]
我还以为 null 会判断成失败的，重新编译了
https://github.com/tty228/luci-app-serverchan/releases/tag/v2.05.2

**Comment by tty228** [comment]
其实如果默认的温度不准的话，可以在高级设置中使用自定义命令
这样子就不需要转义特殊字符了
`cat /sys/class/thermal/thermal_zone0/temp|sort -nr|head -n1|cut -c-2`
