### ISSUE TITLE
能不能指导下如何添加自定义的方式

### ISSUE THREAD

**Issue by testwhite** [tty228/luci-app-serverchan#221]
wenhook自定义的添加方式

**Comment by tty228** [comment]
https://github.com/zzsj0928/luci-app-pushbot

**Comment by testwhite** [comment]
没看到有相关的文档介绍呀。

**Comment by tty228** [comment]
飞书不是直接可用吗？不需要自定义吧

**Comment by testwhite** [comment]
我搞的群晖chat，不过好像是不支持json格式要求的是text/plain    payload={“text”:"xxxxxxxxxx"}

**Comment by tty228** [comment]
{“text”:"xxxxxxxxxx"} 不就是 json 格式吗
curl -X POST -H "$content_type" -d json文件路径 URL

**Comment by testwhite** [comment]
使用了这种方式，路由里面直接请求是没问题的，但是在全能自定义参数里面就提示token错误
![image](https://github.com/tty228/luci-app-serverchan/assets/31587423/093db335-7fda-4979-9a50-82dc823b5d57)
（上面是路由里面请求的）
![image](https://github.com/tty228/luci-app-serverchan/assets/31587423/b0275722-6e83-4cd2-bf71-dbc6ff2c7a16)
这个是全能推送的日志

**Comment by testwhite** [comment]
感谢大佬

**Comment by testwhite** [comment]
要求的格式为text/plain

**Comment by testwhite** [comment]
{
	"url": "xxxx",
	"data":"@${tempjsonpath}",
	"content_type": "Content-Type: text/plain",
	"str_title_start": "<b>",
	"str_title_end": "</b>",
	"str_linefeed": "\\n",
	"str_splitline": "\\n----\\n",
	"str_space": " ",
	"str_tab": "    ",
	"type": {
		"payload":"{\"text\": \"xxxxxxxxxx\"}"
	}
}


测试postman是正常的
![image](https://github.com/tty228/luci-app-serverchan/assets/31587423/992a3d97-84e5-472a-b891-21c0f69acbf1)
全部推送提示是成功的但是客户端没有接收到信息
![image](https://github.com/tty228/luci-app-serverchan/assets/31587423/63bc8ae0-dc0b-4f33-9e60-5342edc6a08b)

**Comment by tty228** [comment]
https://www.json.cn/

json 格式不对

**Comment by testwhite** [comment]
{
	"url": "https://xxxx.com",
	"data":"@${tempjsonpath}",
	"content_type": "Content-Type: text/plain",
	"str_title_start": "<b>",
	"str_title_end": "</b>",
	"str_linefeed": "\\n",
	"str_splitline": "\\n----\\n",
	"str_space": " ",
	"str_tab": "    ",
	"type": {
		"payload":"{\"text\": \"xxxxxxxxxx\"}"
	}
}

**Comment by testwhite** [comment]
![image](https://github.com/tty228/luci-app-serverchan/assets/31587423/e03c3db2-0325-4d0a-9728-4a7ab032232d)

**Comment by tty228** [comment]
https://www.sojson.com/simple_json.html
那个网站有问题，  {} 两边不应有双引号

**Comment by testwhite** [comment]
大佬有联系方式吗？我的q 2523030730
