### ISSUE TITLE
js版本在定时推送到TG的时候推送成功，但是tg接收到的是报错信息。

### ISSUE THREAD

**Issue by zcluo** [tty228/luci-app-serverchan#223]
【XX软路由】XX软路由
----
2023-05-12 14:41:45
----
 我遇到了一个难题
    定时发送选项错误，你没有选择需要发送的项目，该怎 么办呢
----

日志如下：
2023-05-12 14:41:44 【定时数据】创建定时任务
2023-05-12 14:41:47 【telegram】定时推送任务完成

**Comment by tty228** [comment]
https://github.com/tty228/luci-app-serverchan/commit/881e6633ecf59ded33d12ae7b28a107e0b289b6b
修过了，莫名其妙的 bug
选项默认值为 1 且设置可选项的时候，网页保存并不会修改设置，造成配置文件读取不到数值，但是 Web 上显示是勾选的
