### ISSUE TITLE
推送的信息里面总计流量：0 bytes 

### ISSUE THREAD

**Issue by ardenyang** [tty228/luci-app-serverchan#224]
感谢作者的这个插件，对于了解Op的运行状态非常有用，但我遇到了推送的信息里面总计流量：0 bytes 的问题。

我的情况是：在群晖上用虚拟机安装的Openwrt。Openwrt版本: 分支: 22.03.5，内核: 5.15.109

ServerChan版本：luci-app-serverchan	git-24.130.45319-b22b2dc
wrtbwmon：1.2.1-12
luci-app-wrtbwmon：git-24.120.56147-e65359f

问题现象：推送tg正常，但信息里面的设备    【xxxx】  192.168.xx.xx
    **总计流量：0 bytes**  在线 14 小时 39 分。

OpenWrt菜单--微信推送--在线设备里面，设备的 总计流量也是0 bytes。

看了日志，也没什么异常。
2023-05-12 12:00:01 【定时数据】创建定时任务
2023-05-12 12:00:08 【telegram】定时推送任务完成

看到介绍里面说：该插件与 Routing/NAT 、Flow Offloading 冲突，开启无法获取流量；怀疑是跟这个地方有关，但不太清楚如何禁用 Routing/NAT 、Flow Offloading。多谢了。

**Comment by tty228** [comment]
如果是原版的 OpenWrt ，那么该选项位于 网络-防火墙
![fhq](https://github.com/tty228/luci-app-serverchan/assets/33397881/3ff6b902-1e4d-4b17-8af4-bb422733095d)

非原版 OpenWrt 可能存在于这里
![微信截图_20230512185028](https://github.com/tty228/luci-app-serverchan/assets/33397881/557b9199-4c90-4cb0-b260-bb60f1fc855c)

注：开启代理软件或单臂路由等也会造成无法识别流量
正常的话大概是这样
![微信截图_20230512184512](https://github.com/tty228/luci-app-serverchan/assets/33397881/377f462f-51c7-41e2-a6ce-7efa479edc1c)
