### ISSUE TITLE
2.07.1后的版本，安装完LUCI看不到

### ISSUE THREAD

**Issue by mjyhj** [tty228/luci-app-serverchan#225]
大雕 QSDK，19.07
最高装到2.07.1，后面的版本装完，LUCI显示不出来

**Comment by tty228** [comment]
基于 js 写的界面，不支持 lua，lua 有空再同步了，下次随便整个依赖写上去禁止安装🤣

**Comment by mjyhj** [comment]
> 基于 js 写的界面，不支持 lua，lua 有空再同步了，下次随便整个依赖写上去禁止安装🤣
> 
> -- 所以我是不是该改个版本号

看到了，可以整成2个分支

**Comment by xibaolai** [comment]
现在最新的编译过后，没有设置界面了。

**Comment by tty228** [comment]
v2.06.2 之后的版本不再支持 LuCI 18.06
如需编译，请使用 openwrt-18.06 分支，拉取源码时请使用 `git clone -b openwrt-18.06 https://github.com/tty228/luci-app-wechatpush.git` 命令

**Comment by himho** [comment]
大佬写个lua版吧！用lede编译的用不了啊！
