### ISSUE TITLE
要怎么改wan检测啊 一直提示网络不通 但是实际网络是有的

### ISSUE THREAD

**Issue by shaoyou11** [tty228/luci-app-serverchan#23]
【！！！！】当前网络不通！停止检测！

要怎么改wan口啊 一直提示网络不通 但是实际网络是有的

**Comment by shaoyou11** [comment]
wan是eth0 我改的

**Comment by tty228** [comment]
通过
`curl -k -s -w "%{http_code}" https://www.163.com  -A "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.47 Safari/536.11" -o /dev/null`
返回值判断网络状态
