### ISSUE TITLE
/etc/rc.common: line 152: /usr/bin/serverchan/serverchan: not found

### ISSUE THREAD

**Issue by OgasakiTomoya** [tty228/luci-app-serverchan#26]
Firmware Version	OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)

opkg安装错误：
Installing luci-app-serverchan (1.22-42) to root...
Configuring luci-app-serverchan.
/etc/rc.common: line 152: /usr/bin/serverchan/serverchan: not found

安装后界面内勾选“启用”并应用保存，仍然提示“serverchan NOT RUNNING”
手动发送无效
界面客户端日志为空

**Comment by tty228** [comment]
使用
`sh -n /usr/bin/serverchan/serverchan` 命令看看什么结果
然后看看文件有没有运行权限

**Comment by tty228** [comment]
root@OpenWrt:~# opkg install /tmp/luci-app-serverchan_1.22-42_all.ipk
Installing luci-app-serverchan (1.22-42) to root...
Configuring luci-app-serverchan.
root@OpenWrt:~# 

我这里一切正常

**Comment by OgasakiTomoya** [comment]
> 使用
> `sh -n /usr/bin/serverchan/serverchan` 命令看看什么结果
> 然后看看文件有没有运行权限

`sh -n /usr/bin/serverchan/serverchan` 命令putty运行无错误反馈。
/usr/bin/serverchan/serverchan 文件权限0766。

**Comment by OgasakiTomoya** [comment]
> root@OpenWrt:~# opkg install /tmp/luci-app-serverchan_1.22-42_all.ipk
> Installing luci-app-serverchan (1.22-42) to root...
> Configuring luci-app-serverchan.
> 
> 我这里一切正常


root@VM_Openwrt:/etc/extra_ipks/serverchan# opkg install luci-app-serverchan_1.2
2-42_all.ipk
Installing luci-app-serverchan (1.22-42) to root...
Configuring luci-app-serverchan.
/etc/rc.common: line 152: /usr/bin/serverchan/serverchan: not found

安装提示如上。

SCKEY网页版测试手动推送有效。

路由端界面提示“serverchan NOT RUNNING”，日志为空。

**Comment by OgasakiTomoya** [comment]
以下是部分设备信息：

Status
System
Hostname	VM_Openwrt
Model	Microsoft Corporation Virtual Machine
Architecture	Intel(R) Xeon(R) CPU E3-1265L V2 @ 2.50GHz
Firmware Version	OpenWrt 18.06.4 r7808-ef686b7292 / LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)
Kernel Version	4.14.131
Uptime	2d 23h 41m 50s
Load Average	0.09, 0.06, 0.01
Memory
Total Available	
212148 kB / 502916 kB (42%)
Free	
135488 kB / 502916 kB (26%)
Buffered	
76660 kB / 502916 kB (15%)

Active DHCP Leases
Hostname	IPv4-Address	MAC-Address	Leasetime remaining
…………	192.168.25.162	…………	0h 53m 19s
…………	192.168.25.161	…………	0h 54m 30s
……

WAN
pppoe-wan
Protocol: PPPoE
Uptime: 2d 23h 49m 46s
MAC: …………………………
RX: 137.30 GB (135322337 Pkts.)
TX: 39.20 GB (103834201 Pkts.)
IPv4: …………………………
IPv6: …………………………

**Comment by L-vivi** [comment]
我是X86_64的，问题跟你的一样，用lean源码编译进去的，无法运行

**Comment by tty228** [comment]
有人说是原版openwrt没有bash，你再编译个试试

**Comment by OgasakiTomoya** [comment]
> 有人说是原版openwrt没有bash，你再编译个试试

确是因为原版没有bash，安装后问题解决。
