### ISSUE TITLE
你好，可以提供一下你k3固件里的高级设置插件吗？

### ISSUE THREAD

**Issue by ntlf9t** [tty228/luci-app-serverchan#3]
你好，可以提供一下你k3固件里的高级设置插件吗？谢谢

本问题和本插件无关，不知道在哪私聊你。

**Comment by tty228** [comment]
主要是不是我的源码，本身我就是没通过别人自己提取的，不太想分享这个
我印象里恩山上有类似的插件，你去恩山找找
