### ISSUE TITLE
serverchan 总计流量不显示

### ISSUE THREAD

**Issue by QiuSimons** [tty228/luci-app-serverchan#30]
这是什么bug，还是说需要什么特定的依赖啊
![9A2C546B-8C4E-4811-BC36-C456C598173E](https://user-images.githubusercontent.com/45143996/72580217-4a7d2280-3916-11ea-88cd-afd62ce38ed1.jpeg)

**Comment by tty228** [comment]
流量统计提取自 luci-app-wrtbwmon，依赖 luci-app-nlbwmon，自行选装
但是你的脚本并没有正常工作，即使不显示也应该是 0bytes
而且设备名没有显示

**Comment by QiuSimons** [comment]
> 流量统计依赖 luci-app-wrtbwmon ，自行选装
> 但是你的脚本并没有正常工作，即使不显示也应该是 0bytes
> 而且设备名没有显示

emm,装上了依赖还是有问题，是还有其他依赖么，我是基于官方正式版的19.07.0编译的

**Comment by QiuSimons** [comment]
> 流量统计依赖 luci-app-wrtbwmon ，自行选装
> 但是你的脚本并没有正常工作，即使不显示也应该是 0bytes
> 而且设备名没有显示

![9F110D8D-EB25-47D8-BD7F-BA6D8BB3865C](https://user-images.githubusercontent.com/45143996/72698189-f96f6780-3b7d-11ea-8db1-e3cf04341917.png)
最新的commit似乎可以工作了，但中间有个断行，很奇怪

**Comment by tty228** [comment]
你运行一下 `cat /var/dhcp.leases` 命令，你的设备名都不能获取的吗
断行也应该是设备名导致的格式问题

**Comment by SimonsQiu** [comment]
> cat /var/dhcp.leases

![微信截图_20200120134311](https://user-images.githubusercontent.com/30074550/72701631-e9aa5000-3b8a-11ea-9e36-432748bf349b.png)

**Comment by binext** [comment]
如果设备是二级路由上过来的，会获取不到设备名

**Comment by QiuSimons** [comment]
> 如果设备是二级路由上过来的，会获取不到设备名

没有二级路由，很奇怪....
还有就是在线设备中间有个奇怪断层很迷

**Comment by binext** [comment]
> 
> 
> > 如果设备是二级路由上过来的，会获取不到设备名
> 
> 没有二级路由，很奇怪....
> 还有就是在线设备中间有个奇怪断层很迷

那就奇怪全部获取不到设备名的问题了，
那个推送中间有个断层，我也出现了。。。

![Screenshot_20200201_125400_com tencent mm](https://user-images.githubusercontent.com/33397660/73587073-9ffa2780-44f1-11ea-8336-9157ce96c95e.jpg)

**Comment by tty228** [comment]
你的断行目测应该是我忘了去重
10.0.0.10跟10.0.0.100读取到两行了

**Comment by binext** [comment]
> 
> 
> 你的断行目测应该是我忘了全字匹配
> 10.0.0.10跟10.0.0.100读取到两行了

OK,fixed

**Comment by QiuSimons** [comment]
谢谢，新编译的我这儿没有这个问题了

**Comment by ASC8384** [comment]
> 流量统计依赖 luci-app-wrtbwmon ，自行选装 但是你的脚本并没有正常工作，即使不显示也应该是 0bytes 而且设备名没有显示

您好，我安装了`luci-app-wrtbwmon`后，依旧没有流量显示，请问该如何解决？
查阅系统进程，有`{wrtbwmon} /bin/sh /usr/sbin/wrtbwmon -46 -f /tmp/usage.db -p /tmp/usage.htm -u /etc/wrtbwmon.user -d`，版本号为`git-22.147.57852-d7e4f23`。
`luci-app-wrtbwmon`版本号为`git-22.174.44819-ca01673`。

![图片](https://user-images.githubusercontent.com/29878345/184321685-6e0fbe9b-eb91-4065-970c-59ae24d9a466.png)
