### ISSUE TITLE
最新更新的版本无法推送系统信息

### ISSUE THREAD

**Issue by kang-mk** [tty228/luci-app-serverchan#37]
最新更新的版本无法推送系统信息
在LEAN和原版OPENWRT上都测试过了
较老的版本luci-app-serverchan_1.0-43_all可以正常推送
最新的luci-app-serverchan_1.27-42 推送没反应，手动推送也一样，只有变更IP的时候能正常推送下IP信息
依赖 iputils-arping + curl 命令这两个组件也都编译的有
环境是X64软路由
在最新编译的版本上把新版serverchan删除，然后IPK安装luci-app-serverchan_1.0-43_all，也可以正常推送
编译版本，和手动IPK安装结果都是一样的

**Comment by tty228** [comment]
我也遇到了
最近加的东西比较多，刚回家，我排查一下

**Comment by kang-mk** [comment]
嗯 有半个多月都没有推送了，一直在忙也没看是哪里问题，今天搞了一下午排除了固件本身的问题

**Comment by tty228** [comment]
可以了

**Comment by kang-mk** [comment]
OK，谢谢回复，晚上编译一版，明天早上起来更新看看

**Comment by kang-mk** [comment]
已经可以了，另外能不能提一个小建议，就是推送时间能不能加一个自定义选项，比如每天早上8点和晚上8点各推送一次？
尝试过直接修改计划任务，但是会被软件又给修改回去

**Comment by tty228** [comment]
可以了，新版本使用推送二

**Comment by kang-mk** [comment]
无法启动? 我重置下serverchan的配置看下
![snipaste20200212_115617](https://user-images.githubusercontent.com/20243226/74301874-72ce3480-4d8f-11ea-8bae-f0792a977d61.jpg)

**Comment by kang-mk** [comment]
![snipaste20200212_115617](https://user-images.githubusercontent.com/20243226/74302355-37cd0080-4d91-11ea-903c-75acb3fb5915.jpg)
原版和LEAN源码编译的固件好像都不能启动
麻烦大佬看下

**Comment by tty228** [comment]
你试一下新源码
如果不行的话，SSH `sh -n /usr/bin/serverchan/serverchan` 看看结果
还有看看详细日志有没有报错

**Comment by kang-mk** [comment]
Ok,我再编译一下看看，辛苦了

**Comment by tty228** [comment]
我这边
`0 10-24/10 * * * /usr/bin/serverchan/serverchan send &`
执行并不成功……变成了4小时一次
![微信截图_20200212134209](https://user-images.githubusercontent.com/33397881/74307463-5be40e00-4da0-11ea-931e-a0cc41d2272d.png)

**Comment by tty228** [comment]
![微信截图_20200212140408](https://user-images.githubusercontent.com/33397881/74307530-92ba2400-4da0-11ea-9c8f-4a74a0a85812.png)
命令应该没有问题啊

**Comment by kang-mk** [comment]
0 8,20 * * * /usr/bin/serverchan/serverchan send &
可以这样吧

**Comment by tty228** [comment]
还不知道，正打算试试……

**Comment by tty228** [comment]
拿分钟试了一下，应该是没问题了……
下次再改

**Comment by kang-mk** [comment]
还是无法运行 奇怪了

**Comment by kang-mk** [comment]
运行 sh -n /usr/bin/serverchan/serverchan 无任何提示

**Comment by kang-mk** [comment]
[luci-app-serverchan_1.31-42_all.zip](https://github.com/tty228/luci-app-serverchan/files/4190913/luci-app-serverchan_1.31-42_all.zip)
很奇怪，新编译 的

**Comment by kang-mk** [comment]
额  已经更新到1.32了？   待会再编译吧

**Comment by tty228** [comment]
主要是困在家里比较无聊……
半个多月没摸到电脑
----
我这边一直是正常的，日志也没有提示的话，这就很蛋疼了
忘了说了，SSH 直接运行 `/usr/bin/serverchan/serverchan`应该会报错的

**Comment by tty228** [comment]
我这边提取出来的文件可以运行……

文件头部改成 #!/bin/bash 试试

**Comment by kang-mk** [comment]
那就很奇怪了  昨天后来更新的是可以正常运行的  今天的就一直未运行
我发你的文件你那边可以运行? 
文件头部改成 #!/bin/bash 试试
没明白怎么改？

**Comment by kang-mk** [comment]
运行 sh -n /usr/bin/serverchan/serverchan 无任何提示

你之前说让运行这个 是没任何提示
  /usr/bin/serverchan/serverchan 
直接运行这个提示没权限   -ash: /usr/bin/serverchan/serverchan: Permission denied  估计就是这里的问题了 
最早的时候不是这个提示的

**Comment by kang-mk** [comment]
好了，默认/usr/bin/serverchan/serverchan这个文件权限是0644，改成0755好了，现在可以运行了
但是这个是什么原因导致的？之前编译一直都是正常的

**Comment by tty228** [comment]
我直到现在都搞不懂 Makefile 的机制
反正时不时就会这样
（但是我的机子上一直是没问题的……）

https://github.com/tty228/luci-app-serverchan/issues/1

**Comment by kang-mk** [comment]
我是第一次遇到这种情况，之前编译的版本都是正常运行的，找到问题就好办了，虽然不知道为什么导致的，但是有解决方法就行，简单粗暴点也没关系

**Comment by KFERMercer** [comment]
我也一直没有问题

**Comment by KFERMercer** [comment]
文件权限问题, 提交修复了↑

**Comment by tty228** [comment]
> 文件权限问题, 提交修复了↑

这个权限是怎么改的？

**Comment by kang-mk** [comment]
@tty228 @KFERMercer  感谢各位大佬  都辛苦了

**Comment by KFERMercer** [comment]
> 这个权限是怎么改的？

chmod 755

**Comment by tty228** [comment]
> > 这个权限是怎么改的？
> 
> chmod 755

不是，我的意思是编译之前怎么修改的（或者我是为什么提交了 644的文件）

**Comment by kang-mk** [comment]
我也没看懂 这种文件是这么更改权限的？完全不懂代码，只是好奇，没看到能修改权限的地方啊

**Comment by KFERMercer** [comment]
某次你是不是直接新建了个文件重写的脚本? 如果一直在一个文件的基础上只修改文本内容, 是不会破坏权限的.

openwrt 的 package build 基本上就是把指定的文件 cp 到指定的位置, 不会更换文件内容. 万物皆文件, 权限掩码也是文件内容的一部分, 所以此权限就是编译后的彼权限.

**Comment by kang-mk** [comment]
是不是在LINUX系统下修改文件权限，然后再上传到GitHub上面就可以了？

**Comment by KFERMercer** [comment]
是

**Comment by kang-mk** [comment]
了解，感谢解答疑惑  总算没问题了

**Comment by tty228** [comment]
明白了，感谢

**Comment by xiaozizi58** [comment]
x64 刚才编译的版本 也遇到你们上面说的权限问题了 自己手动去改了
 然后看日志  有这个报错cat: can't open '/tmp/serverchan/usage.db': No such file or directory
不过使用上没什么问题

**Comment by KFERMercer** [comment]
make clean

**Comment by tty228** [comment]
> usage.db

这个应该是没有安装 luci-app-wrtbwmon
查看设备流量情况需要这个依赖
不影响其他功能

不过我要检查一下是哪里没验证文件是否存在就读取了

**Comment by kang-mk** [comment]
可以加一个推送的时候是否连客户端的流量信息一起推送的开关，如果路由开了Flow Offloading，会造成wrtbwmon的流量统计完全无效，那么一起推送了，完全没有意义，在线时间倒是没关系

**Comment by kang-mk** [comment]
提了一大堆问题，大佬这两天忙坏了，辛苦

**Comment by tty228** [comment]
我这边开启 Flow Offloading 不影响流量统计，不过不需要这个功能的话删掉 wrtbwmon 就行了
wrtbwmon 不可用的情况下不会再出现总计流量的文字了

**Comment by kang-mk** [comment]
![Screenshot_2020-02-12-21-50-17-379_com mmbox xbrowser pro](https://user-images.githubusercontent.com/20243226/74343521-2b26c780-4de6-11ea-9b42-789417a4b21e.jpg)
我这里只要打开，wrtbwmon的流量统计就完全失效了，统计出来的数据都是几K几K的，关闭加速之后正常，难道是我编译的有问题？

**Comment by tty228** [comment]
![1](https://user-images.githubusercontent.com/33397881/74347109-8effbf00-4deb-11ea-8115-1a9acf53b7ed.png)
![微信截图_20200212230043](https://user-images.githubusercontent.com/33397881/74347123-932bdc80-4deb-11ea-80c4-8644a1806b26.png)

我打开了 Flow Offloading 转发加速 的确不影响流量统计
硬件HWNAT加速 就不知道了，K3 应该不支持

**Comment by tty228** [comment]
感觉跟编译没关系吧，要不是设备原因要不是源码问题

**Comment by kang-mk** [comment]
我是软路由，L大和原版都一样

**Comment by kang-mk** [comment]
luci-app-nlbwmon和wrtbwmon有关联吗？会不会是这个设置的问题？用的默认设置，路由ip是10.0.0.1
![Screenshot_2020-02-12-23-45-47-029_com mmbox xbrowser pro](https://user-images.githubusercontent.com/20243226/74351239-d426ef80-4df1-11ea-9ee9-370cb07dd0b9.jpg)

**Comment by tty228** [comment]
wrtbwmon 依赖 nlbwmon 
我默认设置没改过
但是你关闭加速之后正常，应该跟这些没关系

**Comment by kang-mk** [comment]
应该是软件加速之后，流量走了另外的通道，wrtbwmon统计不到了，就跟ssr的流量它也一样统计不到

**Comment by tty228** [comment]
[是硬件加速的锅](https://github.com/coolsnowwolf/lede/issues/2869)

**Comment by kang-mk** [comment]
嗯  那就无解了，只能二选一了，类似原来折腾爱快的时候，用爱快做二级路由流控的时候好像也遇到这个问题，它有一个路由模式和NAT模式，忘记哪个模式对于哪种情况了，反正是一种模式所有的流量都会从爱快过，如果用另外一种模式，爱快好像就不过流量，但是两种情况流控都是有效的，就跟现在wrtbwmon的情况一样，不从它这边过，它就统计不到对应的流量了
开了科学上网，海外流量我实际测试过wrtbwmon也统计不到

**Comment by kang-mk** [comment]
我百兆带宽，昨天实际测试过Flow Offloading开与不开，CPU占用率有3-7%左右的差距，而且平时大部分情况下是跑不满带宽的，综合下来，其实差距就更小了

**Comment by tty228** [comment]
然后昨天试过之后才发现，BBR 不只是影响 wifi 吞吐量，还会降低 samba 的传输速度
