### ISSUE TITLE
跨日开了免打扰，定时推送没被阻止

### ISSUE THREAD

**Issue by binext** [tty228/luci-app-serverchan#38]
免开始打扰时间设置成22点，免打扰结束时间设置成8点，结果还是推送了。
刚看到更新了1.30，看了下，貌似修复了？

另外，日志是否可以在时间前面增加日期，日志太多了，不知道是哪一天的了。

**Comment by tty228** [comment]
并没有修复，之前改了一下免打扰的判断顺序
然后定时任务中忘了加免打扰检测了

**Comment by tty228** [comment]
可以了
