### ISSUE TITLE
跟koolshare软件中心的severchan是一个项目吗？

### ISSUE THREAD

**Issue by leo8912** [tty228/luci-app-serverchan#39]
如果不是，可以参考一下啊，ks上的信息更详细更方便。。希望能借鉴

**Comment by kang-mk** [comment]
明显不是一个

**Comment by tty228** [comment]
想当初……我就是没找到源码才重新造了轮子
![微信截图_20200212134209](https://user-images.githubusercontent.com/33397881/74306457-854f6a80-4d9d-11ea-9ce8-cacbe58e91b0.png)

**Comment by kang-mk** [comment]
ks闭源的，木有源码

**Comment by leo8912** [comment]
> 
> 
> 想当初……我就是没找到源码才重新造了轮子
> ![微信截图_20200212134209](https://user-images.githubusercontent.com/33397881/74306457-854f6a80-4d9d-11ea-9ce8-cacbe58e91b0.png)

原来如此。。。那个信息确实多一点，，，
https://github.com/koolshare/ledesoft/tree/master/serverchan
这个是源码吗？

**Comment by tty228** [comment]
这个是软件中心的安装代码，里面没有可见的脚本源码
