### ISSUE TITLE
其他设备温度获取具体怎么改呢？

### ISSUE THREAD

**Issue by bin20088** [tty228/luci-app-serverchan#40]
你好，我是X86，你的源码说其他设备温度自行修改那个代码，具体怎么改啊能指导一二不？

**Comment by tty228** [comment]
你试试新版能不能获取温度，如果不行的话，替换 /usr/bin/serverchan/serverchan 中的
`cut -c1-2 /sys/class/thermal/thermal_zone0/temp` 命令

**Comment by tty228** [comment]
更新了版本，现在获取温度的命令在 506 行
`cat /sys/class/thermal/thermal_zone*/temp | sort | sed '$!d' | cut -c-2`


`#获取SOC温度
function soc_temp(){
	cat /sys/class/thermal/thermal_zone*/temp | sort | sed '$!d' | cut -c-2
	# 取所有传感器数值中的最大值
}`

**Comment by bin20088** [comment]
搞定  多谢
