### ISSUE TITLE
1.33-42安装提示：uci：entry not found

### ISSUE THREAD

**Issue by leo8912** [tty228/luci-app-serverchan#43]
如题。。
X64内核版本4.19.101

**Comment by tty228** [comment]
一般是配置文件问题，备份一下 key ，删除配置文件重新安装试试

**Comment by leo8912** [comment]
> 
> 
> 一般是配置文件问题，备份一下 key ，删除配置文件重新安装试试

配置文件在哪？删除了/usr/bin/serverchan文件夹重新安装还是这样

**Comment by tty228** [comment]
/etc/config/serverchan

**Comment by leo8912** [comment]
> 
> 
> /etc/config/serverchan

仍然是这样。。。。

**Comment by leo8912** [comment]
> 
> 
> > /etc/config/serverchan
> 
> 仍然是这样。。。。

删除后安装现在/etc/config/这个文件夹下没有serverchan文件了

**Comment by tty228** [comment]
卸载重装呢？
[参考1](https://github.com/tty228/luci-app-serverchan/issues/27)
[参考2](https://github.com/tty228/luci-app-serverchan/issues/24)

**Comment by leo8912** [comment]
> 
> 
> 卸载重装呢？
> [参考1](https://github.com/tty228/luci-app-serverchan/issues/27)
> [参考2](https://github.com/tty228/luci-app-serverchan/issues/24)

重新安装无效，仍然报错，
按你参考2里的，以下两条命令都报错
uci get serverchan.serverchan.sckey
uci get serverchan.@serverchan[0].sckey
不过uci show serverchan不报错
下面是/etc/config/serverchan文件内容：
config serverchan 'serverchan'
	option serverchan_ip '1'
	option serverchan_down '1'
	option serverchan_sleeptime '60'
	option sheep_enabled '1'
	option temp_mask '1'
	option cpuload_enable '1'
	option temperature_enable '1'
	option serverchan_ipv6 '0'
	option serverchan_sheep '0'
	option cpuload '2'
	option send_enable '0'
	option serverchan_enable '0'
	option serverchan_ipv4 '0'
	option serverchan_up '1'
	option up_timeout '2'
	option down_timeout '10'


另外/dev/null 2>&1是个命令吗？输入这个命令显示Permission denied
，所以报错是权限有问题？

**Comment by tty228** [comment]
uci：entry not found 报错是因为读取不到相关的设置选项
serverchan.serverchan.sckey 默认就是空的，这个是正常的
/dev/null 2>&1 的意思是无论报错还是正常运行，都不显示任何信息

可能编译环境缓存的问题吧，我重新上传一下
----
如果不是的话，我暂时不知道什么原因了

**Comment by leo8912** [comment]
> 
> 
> uci：entry not found 报错是因为读取不到相关的设置选项
> serverchan.serverchan.sckey 默认就是空的，这个是正常的
> /dev/null 2>&1 的意思是无论报错还是正常运行，都不显示任何信息
> 
> 可能编译环境缓存的问题吧，我重新上传一下
> 
> 如果不是的话，我暂时不知道什么原因了

那就等你的更新了

**Comment by leo8912** [comment]
> 
> 
> uci：entry not found 报错是因为读取不到相关的设置选项
> serverchan.serverchan.sckey 默认就是空的，这个是正常的
> /dev/null 2>&1 的意思是无论报错还是正常运行，都不显示任何信息
> 
> 可能编译环境缓存的问题吧，我重新上传一下
> 
> 如果不是的话，我暂时不知道什么原因了

应该不是这样，我自己编译了也是报错。。。等你下个版本再试吧

**Comment by HofmannHe** [comment]
luci-app-serverchan_1.35-5_all.ipk复现上述问题
>root@OpenWrt:/usr/lib/opkg/info# /usr/bin/serverchan/serverchan
>uci: Entry not found
>uci: Entry not found
>sh: out of range
>sh: out of range
能正常执行uci show serverchan

**Comment by tty228** [comment]
[temp.zip](https://github.com/tty228/luci-app-serverchan/files/4241463/temp.zip)

你试试把这个文件放到 tmp 目录运行看看结果

**Comment by HofmannHe** [comment]
> [temp.zip](https://github.com/tty228/luci-app-serverchan/files/4241463/temp.zip)
> 
> 你试试把这个文件放到 tmp 目录运行看看结果

这个temp文件可以执行成功，不报错

**Comment by tty228** [comment]
那个是变量打错了
之前因为 uci 报错，加了 get_config() ，`uci show serverchan` 找到变量之后才会读取，但是依然报错
不知道问题在哪，大概可能系统不一样哪里语法不通用
如果你懂 shell 语言的话，可以尝试 `sh -x /usr/bin/serverchan/serverchan` 查错
