### ISSUE TITLE
多WAN下的定时推送，IPV6地址检测不是按默认路由或者选择的接口出去的

### ISSUE THREAD

**Issue by elfive** [tty228/luci-app-serverchan#44]
我目前是一条电信宽带（pppoe-wan1）和4G（wwan0）两条线路按故障转移策略接入的互联网的，两条线路都有IPv4和IPv6地址及IPv6-PD前缀。
![85CDD322-886E-4377-BF8C-C54719B34593](https://user-images.githubusercontent.com/12877854/74584152-090d8f00-500a-11ea-999e-3a9e80b6820a.jpeg)

分流规则设定的是优先使用电信宽带，在serverchan插件里面也是选择从电信宽带接口（pppoe-wan1）获取IPv4和IPv6地址的。
![82648D3A-7F9F-44AC-B267-2EC7AA3B1E72](https://user-images.githubusercontent.com/12877854/74584155-11fe6080-500a-11ea-90f2-5941fb76bd61.jpeg)

如图所示问题在于：
1. 定时推送的消息，无法显示IPv4接口（pppoe-wan1）地址，只会显示IPv4外网地址；
2. 定时推送的消息，IPv6接口地址（pppoe-wan1）能正确显示，但是IPv6外网地址则会从ifconfig显示的第一个wan接口（我这里就是4G的wwan0接口）的IPv6地址，由于接口都不同了，所以自然会提示我的IPv6地址不是公网地址。

![361194AF-28F6-4F34-9AB5-661137DC8526](https://user-images.githubusercontent.com/12877854/74584052-ea5ac880-5008-11ea-9c88-e58d6d217478.jpeg)

**Comment by tty228** [comment]
我这边没有多拨环境，延后再尝试修复吧
不过 ipv6 外网 ip 的获取应该是弄不好了，不知道有没有命令强制使用选择的借口访问 ip 查询网站

**Comment by elfive** [comment]
如果是curl的话，可以使用--interface <interface>指定接口
如果是使用wget的话，可以使用--bind-address=<接口IP>指定接口

**Comment by tty228** [comment]
了解

**Comment by elfive** [comment]
刚刚远程试了一下，curl的interface参数，提供绑定接口的IP地址能用，如果提供绑定接口的名称，就不能用。不知道为啥。我对Linux不是很熟悉，Openwrt/LEDE也只是会用的级别，加上手上现在也没电脑，不方便测试，这两天就不提PR了。

**Comment by tty228** [comment]
你试试
`ubus call network.interface.wan status`命令，然后发一下结果

**Comment by tty228** [comment]
IPV6的改成这样试试

ipv6_interface=`get_config ipv6_interface`
send_hostIPv6=$(curl -k -s -6 --interface $ipv6_interface  v6.ip.zxinc.org/getip)

**Comment by tty228** [comment]
然后你试试这个命令，看看IPV6是否正常
`/sbin/ifconfig pppoe-wan | awk '/inet6/ /Global/ {print $3}'`

**Comment by elfive** [comment]
那条命令运行错误了
> root@LEDE:\~# /sbin/ifconfig pppoe-wan1 | awk '/inet6/ /Global/ {print $3}'
awk: cmd. line:1: Unexpected token
root@LEDE:\~# ifconfig pppoe-wan1
pppoe-wan1 Link encap:Point-to-Point Protocol  
          inet addr:175.0.***.***  P-t-P:175.0.***.***  Mask:255.255.255.255
          inet6 addr: 240e:380:****:****:****:****:8:57bb/64 Scope:Global
          inet6 addr: fe80::****:****8:57bb/10 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
          RX packets:6408209 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5087434 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:4814014829 (4.4 GiB)  TX bytes:2036714991 (1.8 GiB)

**Comment by tty228** [comment]
> 那条命令运行错误了
> 
> > root@LEDE:~# /sbin/ifconfig pppoe-wan1 | awk '/inet6/ /Global/ {print $3}'
> > awk: cmd. line:1: Unexpected token
> > root@LEDE:~# ifconfig pppoe-wan1
> > pppoe-wan1 Link encap:Point-to-Point Protocol
> > inet addr:175.0.***.***  P-t-P:175.0.***.***  Mask:255.255.255.255
> > inet6 addr: 240e:380: ***:*** : ***:***:8:57bb/64 Scope:Global
> > inet6 addr: fe80::***:*** 8:57bb/10 Scope:Link
> > UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1492  Metric:1
> > RX packets:6408209 errors:0 dropped:0 overruns:0 frame:0
> > TX packets:5087434 errors:0 dropped:0 overruns:0 carrier:0
> > collisions:0 txqueuelen:3
> > RX bytes:4814014829 (4.4 GiB)  TX bytes:2036714991 (1.8 GiB)

那个是打错的。。请忽略

**Comment by tty228** [comment]
OK ，看到结果了

**Comment by tty228** [comment]
inet6 addr: 240e:380: ***:*** : ***:***:8:57bb/64 Scope:Global

这个地址是对的吧

**Comment by elfive** [comment]
没错，辛苦了。抱歉也没能帮上啥忙。

**Comment by tty228** [comment]
你把脚本文件 /usr/bin/serverchan/serverchan 覆盖试试

**Comment by tty228** [comment]
稍稍晚点，语法好像错了，而且没考虑没加上接口的情况

**Comment by elfive** [comment]
测试了下，IPv4正常了，但是由于IPv6的interface是pppoe-wan1，所以我这里显示不了IPv6地址，只能通过绑定接口（pppoe-wan1）的IPv6地址才能正常运行。

![B1A198B7-8986-4AE0-B702-FF65D0910970](https://user-images.githubusercontent.com/12877854/74588715-cfed1300-5039-11ea-866c-a0329f59b017.jpeg)

**Comment by elfive** [comment]
> 稍稍晚点，语法好像错了，而且没考虑没加上接口的情况

好的。

**Comment by elfive** [comment]
昨天试了一下 [#ae69596](https://github.com/tty228/luci-app-serverchan/commit/ae69596819619791826204cfe79686d1d72d4718) 这个提交。
IPv4正常，IPv6接口地址正确显示，IPv6外网地址空白。原因还是因为curl --interface 参数绑定接口名称导致的，如果改成绑定接口的IPv6地址，就没问题了。

我的改动如下：
serverchan第544行
由
`if [ ! -z "$ipv6_interface" ] ; then send_hostIPv6=$(curl -k -s -6 --interface $ipv6_interface $ipv6_URL);fi`
改为
`if [ ! -z "$ipv6_interface" ] ; then send_hostIPv6=$(curl -k -s -6 --interface $send_wanIPv6 $ipv6_URL);fi`
