### ISSUE TITLE
1.33-42版本第一次保存应用不能运行，需第二次点击保存应用，1.28-42版本正常！

### ISSUE THREAD

**Issue by zxlhhyccc** [tty228/luci-app-serverchan#47]
![image](https://user-images.githubusercontent.com/45259624/74601055-7685f200-50d4-11ea-9a23-e42502fc1a41.png)

**Comment by tty228** [comment]
是第一次运行还是每次都这样？
我这边没问题啊

**Comment by zxlhhyccc** [comment]
> 是第一次运行还是每次都这样？
> 我这边没问题啊

每次都这样。。。。

**Comment by Twinzo1** [comment]
你的openwrt应该是官方版本

**Comment by tty228** [comment]
luci 19.07 并未发现此问题
