### ISSUE TITLE
可否把推送的负载改成或增加个CPU使用率？

### ISSUE THREAD

**Issue by abclai** [tty228/luci-app-serverchan#49]
可否把推送的负载改成或增加个CPU占有率？

两个L大的固件都增加了CPU使用率这个项目啦！可否把负载改成增加CPU使用率供用户选择？

负载我一直没搞明白是啥，CPU使用率还看明白点啦！

**Comment by tty228** [comment]
显示占用率倒是可以，之前有做只是注释了
因为有一个问题，以路由器的 cpu，连续几条命令就可以让cpu占用率达到100%
看起来也很尴尬，不如看负载
负载的话，不超过核心数*1 都算健康的，超过的话，就意味着新的进程需要排队等待处理
![微信图片_20200219041717](https://user-images.githubusercontent.com/33397881/74774454-badce200-52ce-11ea-8fe5-3bb13ec0d5c3.png)

**Comment by tty228** [comment]
不知道lean大那个是什么文件生成的，感觉比上面的命令精准

**Comment by tty228** [comment]
刷了网页版的看了一下，L大那个是通过 /proc/stat 计算的，比 top 精准得多，下次再加上吧
