### ISSUE TITLE
最新的提交是画蛇添足

### ISSUE THREAD

**Issue by KFERMercer** [tty228/luci-app-serverchan#50]
没必要为了解决一个**不存在的问题**来破坏包的目录结构, 然后重新造轮子来实现**官方已有的机制**.

如果只是为了保证脚本文件有运行权限, 只需要在install变量的最后添加:
```shell
chmod 755 $(1)/usr/bin/serverchan
```
**必须要说明的是, 这段代码要解决问题并不存在.**

---

如果编译前的文件权限正确且编译环境没有被污染, 就不会出现权限问题.
如果在测试发现没有运行权限, 但是文件源码目录下的文件权限正常, 那么就应该检查编译缓存下的文件权限信息:

```shell
ls -l ./build_dir/.../luci-app-zerotier/root/usr/bin/
```
这里的文件和最终编译进固件的文件完全相同, 如果确实没有运行权限, 说明需要make clean.

**Comment by KFERMercer** [comment]
我觉得这个问题已经翻篇了

**Comment by tty228** [comment]
就这样吧→_→，作为一个野生自学的菜鸡，不良编程习惯太多（我已经不记得几次上传错误的文件了，虽然都是在你提醒我之前）
主要是昨天看了一下 Makefile 的说明，就干脆照说明重新写了
因为不知道加上 chmod 755 $(1)/usr/bin/serverchan 就完事了
改文件夹名字什么的……主要是觉得好看……

**Comment by KFERMercer** [comment]
最好的说明是去看官方的实例. 

这种让别人去破坏文件结构, 手动指定编译目录, 降低的版本号的说明给人感觉很不专业
