### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by zlr1** [tty228/luci-app-serverchan#51]
安装luci-app-serverchan_1.35-5_all.ipk报错，提示如下：
root@OpenWrt:/tmp# opkg install luci-app-serverchan_1.35-5_all.ipk
Installing luci-app-serverchan (1.35-5) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-serverchan:
 * 	iputils-arping
 * opkg_install_cmd: Cannot install package luci-app-serverchan.
root@OpenWrt:/tmp# 
请大佬给出解决方案，谢谢！
固件版本	OpenWrt 19.07-SNAPSHOT / LuCI 18-Lienol (git-20.050.67398-912fbd7)
内核版本	4.14.169

**Comment by tty228** [comment]
没有 `opkg update` 或不支持 iputils-arping 依赖
