### ISSUE TITLE
检测ip变更有bug

### ISSUE THREAD

**Issue by kkshen1** [tty228/luci-app-serverchan#52]
检测ip变更时候 获取不到上次检测的ip 然后就一分钟发送一次ip变更 

看日志 试了接口获取url获取能获取到ip 但好像不记录 下次检测变更 显示上次ip是空白的 所以重复发ip变更实际是没变

**Comment by kang-mk** [comment]
是的，已经遇到了，刚刚刷新了下最新固件，然后这样了  不停的发送变更IP的信息给我

**Comment by kang-mk** [comment]
只能暂时关闭了

**Comment by kkshen1** [comment]
我退回老版本就好了

**Comment by kang-mk** [comment]
不着急  等大佬修复  明天重新刷机下就可以了

**Comment by xiaozizi58** [comment]
不止这样 自己备注的客户端名字不显示 显示为一串数字  先回上一版吧 我用上一版没什么问题

**Comment by tty228** [comment]
好了，昨天看到有些地方没全字匹配，手贱加了上去，grep -q（不提示信息输出） -i（忽视大小写） -w（全字匹配）
造成无法读取
然后我机子里的居然测试的是没改动的版本

**Comment by kang-mk** [comment]
重新frok了一下  辛苦了
