### ISSUE TITLE
卡成狗，LUCI关闭了，进程都没杀

### ISSUE THREAD

**Issue by mjyhj** [tty228/luci-app-serverchan#55]
http://chuantu.xyz/t6/721/1582810221x992245926.png

看图

**Comment by jelly0925** [comment]
N1 刷怕OpenWrt R20.2.15 固件，只要打开微信推送服务路由器的CPU使用率就会升级到100%，在界面把微信推送开关关闭也不能结束服务，只能重启路由器希望作者有时间修复一下，谢谢

**Comment by zhyreng** [comment]
我的也发生了，设备软硬件型号：

主机名 | OpenWrt
-- | --
主机型号 | Phicomm N1 (CpuMark : 18040.026308 Scores)
架构 | ARMv8 Processor rev 4 (v8l) x 4
固件版本 | OpenWrt Development Snapshot / LuCI Master (git-20.051.42827-3e80fef)
内核版本 | 5.4.22-amlogic-flippy-27+

出现5个进程，把cpu吃到100，之前几天正常，突然飙高到100，很纳闷，进ssh一看，发现有5个serverChan进程，有4个进程分别占用20%以上的cpu。管理UI停用，对进程没影响。kill掉5个进程才恢复正常。通过UI启动，再查进程显示一个，不知道什么时候会再出现多个，特殊的设置是免打扰时段的消息堆压到结束后再发。

**Comment by tty228** [comment]
可能是并发的后台进程遇到了什么问题，导致循环读取写入文件锁
光是ping命令不应该造成这么高的消耗
没有日志不好判断

**Comment by zhyreng** [comment]
又卡了，请问下日志存放位置。插件的日志选项卡是空的。

**Comment by tty228** [comment]
明天我临时修复一下吧
或者你覆盖脚本试试会不会卡
/usr/bin/serverchan
[serverchan.zip](https://github.com/tty228/luci-app-serverchan/files/4288303/serverchan.zip)

**Comment by zhyreng** [comment]
![image](https://user-images.githubusercontent.com/6140981/76064074-ec8ac400-5fc3-11ea-8775-2e4b8f3baf72.png)
卡的时候进程是这样的

**Comment by zhyreng** [comment]
替换了，启用没有运行，是不是哪里还需要设置，权限是755



在 2020-03-05 00:07:36，"tty228" <notifications@github.com> 写道：

明天我临时修复一下吧
或者你覆盖脚本试试会不会卡
/usr/bin/serverchan
serverchan.zip

**Comment by zhyreng** [comment]
![image](https://user-images.githubusercontent.com/6140981/76064791-548dda00-5fc5-11ea-93c7-1939881135b6.png)
这是启动报错信息

**Comment by zhyreng** [comment]
![image](https://user-images.githubusercontent.com/6140981/76067697-c74d8400-5fca-11ea-8c94-28f8c25775bd.png)
这是启动报错信息
