### ISSUE TITLE
版本1.40-5 路由器x64 添加的备注显示unknown.之前版本修复了 现在又有了

### ISSUE THREAD

**Issue by xiaozizi58** [tty228/luci-app-serverchan#56]
版本1.40-5 添加的备注显示unknown.之前版本修复了 现在又有了

**Comment by xiaozizi58** [comment]
同时也无法获取mac地址

**Comment by tty228** [comment]
因为之前的版本是获取不到会一直重试
我用的时候感觉没什么效果，而且有点浪费时间
就移除了，无法获取mac地址的话，显示的备注就找不到

**Comment by xiaozizi58** [comment]
前两天编译的版本就挺好 最新这个没法用了 其他路由器我不知道 我用的是lean的源码编译的 过来反馈一下
