### ISSUE TITLE
lean源码集成server酱编译，uhttpd[1726]: uci: Entry not found

### ISSUE THREAD

**Issue by huah0235** [tty228/luci-app-serverchan#57]
大佬你好，近期利用lean大雕r20.2.15源码编译了k3固件，恩山贴:https://www.right.com.cn/forum/thread-2663715-1-1.html
添加了您的server酱，昨天测试推送什么的都正常，但是日志里不停的刷屏uhttpd[1726]: uci: Entry not found。把server酱关掉就不再报错。看了之前有人推的issue，
uci show serverchan
uci get serverchan.@serverchan[0].sckey
uci get serverchan.serverchan.sckey
这三个命令都能正常输出。
本人尝试修改了一些地方，但是水平有限，没有弄好，求大佬解释，万分感谢!
![Screenshot_20200301_072503_com android chrome](https://user-images.githubusercontent.com/24620648/75616617-29068c00-5b8e-11ea-959d-c79fd45a223a.jpg)
![Screenshot_20200301_072734](https://user-images.githubusercontent.com/24620648/75616618-2c9a1300-5b8e-11ea-8542-0b22fc525c5f.jpg)

**Comment by tty228** [comment]
不怕告诉你，我完全不知道这个问题是怎么产生的
我试过 `2>/dev/null` 禁用错误信息
试过先 uci show 确认有配置条目再读取
但是都会有人报告说出现这个问题
然而我本机环境没出现过，所以我无法查错
你试试新版本会不会出问题吧

如果要查错的话，可以直接运行 `sh -x /usr/bin/serverchan/serverchan` 查看详细命令输出状态
或者修改 function get_config()
# 读取设置文件
function get_config(){
	if [ "$1" ] ;then
		echo $1
		uci get serverchan.serverchan.$1 2>/dev/null
	fi
}
然后命令行运行，看看到底查询哪个配置的时候出的错

![微信截图_20200301155645](https://user-images.githubusercontent.com/33397881/75621926-9b4e8f00-5bd5-11ea-9173-7591633050c7.png)

**Comment by huah0235** [comment]
我拉了最新版1.4重新编译，不报错了，好奇怪

**Comment by tty228** [comment]
那就应该是 echo 的问题了
