### ISSUE TITLE
这两天更新后重启路由器插件不自启，白村配置要点两下确定才能起动，问题越来越多喽

### ISSUE THREAD

**Issue by bin20088** [tty228/luci-app-serverchan#58]
X86，集成进Lean的源码里编译的固件。这两天更新后发现两个问题：
1、重启路由器插件不自启，再进去保存应用一次才能启动。
2、刚开始配置好后保存应用要点两下才能起动。
这两天之前的是正常的，希望能修复

**Comment by xiaozizi58** [comment]
daemon.err uhttpd[1960]: Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_next_proto_select_cb: symbol not found
daemon.err uhttpd[1960]: sh: write error: Broken pipe
daemon.err uhttpd[1960]: command failed: No such device (-19)

这是开启后的系统日志

**Comment by bin20088** [comment]
日志一模一样  多谢补充  好让大佬分析

> daemon.err uhttpd[1960]: Error relocating /usr/lib/libcurl.so.4: SSL_CTX_set_next_proto_select_cb: symbol not found
> daemon.err uhttpd[1960]: sh: write error: Broken pipe
> daemon.err uhttpd[1960]: command failed: No such device (-19)
> 
> 这是开启后的系统日志

**Comment by tty228** [comment]
重启路由器插件不自启是因为启动顺序我排到最后了，其他进程都启动才会启动
luci 无法启动的话，我更新了 19.07 ，有空可以尝试修复了

**Comment by bin20088** [comment]
@tty228 修复到启动不了 emmmm

**Comment by tty228** [comment]
> @tty228 修复到启动不了 emmmm

我这边已经没问题了啊……

你命令行能启动吗

**Comment by bin20088** [comment]
@tty228 我用的大雕的源码编译的X86.之前点两边保存应用就好了，虽然不停地推送在线设备。下载点N遍也启动不了。所以又回退老版本了    没用命令行试呢

**Comment by bluestar800** [comment]
我也出现了这个情况，我进入init.d里，把serverchan改成现在这个1.42版本的启动命令了，重启了一下使用lean编译的lede，就可以启动了。原来的版本是昨天下午同步的，start里有判断语句，估计是这个判断导致不能自启，只能手动执行一次

**Comment by tty228** [comment]
> 我也出现了这个情况，我进入init.d里，把serverchan改成现在这个1.42版本的启动命令了，重启了一下使用lean编译的lede，就可以启动了。原来的版本是昨天下午同步的，start里有判断语句，估计是这个判断导致不能自启，只能手动执行一次

但是他俩现在的版本也不能启动

**Comment by bin20088** [comment]
@tty228 启动不了的问题找到了，是你的老毛病又犯了。哈哈      还是那两个文件的权限问题。改了就好了

**Comment by xiaozizi58** [comment]
我使用最新版本 没有什么问题 lean源码 x64

**Comment by kang-mk** [comment]
今天更新了一下固件也出现了不能开机自启，需要多次应用保存才能启动的问题，多次确认之后可以启动， 所以应该也不是权限的问题
