### ISSUE TITLE
请教温度sensors命令，如何集成？

### ISSUE THREAD

**Issue by icephonix** [tty228/luci-app-serverchan#59]
命令输出结果如下：
root@OpenWrt:~# sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +33.0°C  (crit = +90.0°C)
请教如何设置脚本，读取温度？

**Comment by tty228** [comment]
`sensors | grep "°C" | awk '{print $3}' | sed $'s/+//g'  | sed $'s/°C//g'`
不使用通配符匹配的话，这样应该可以了，通配符写得比较渣，怕没写好不好调试，就不写了→_→
`grep "°C"` 选取 "°C" 所在的行
`awk '{print $3}'` 选取该行第三列
`sed $'s/+//g'` 移除“+”字符
`sed $'s/°C//g'`移除“°C”字符

`# 获取SOC温度`
`function soc_temp(){`
	`sensors | grep "°C" | awk '{print $3}' | sed $'s/+//g'  | sed $'s/°C//g'`
`}`

![2020-03-06_091759](https://user-images.githubusercontent.com/33397881/76040805-576bd900-5f8b-11ea-92ba-3f84150013dc.png)

**Comment by icephonix** [comment]
可以了，非常感谢！！！你的这个工具太有用了！！！
