### ISSUE TITLE
在MTK7621固件中无法启动

### ISSUE THREAD

**Issue by lllrrr** [tty228/luci-app-serverchan#6]

**Comment by lllrrr** [comment]
在X86固件中可以正常启动

**Comment by hong0980** [comment]
还是那两个文件的权限没有改，改成755就能运行了。

**Comment by XwbCHN** [comment]
> 还是那两个文件的权限没有改，改成755就能运行了。

请问一下是哪两个文件需要改权限呢？我刚编译好 发现无法启动 也是mt7621平台

**Comment by hong0980** [comment]
chmod 755 /etc/init.d/serverchan
chmod 755 /usr/bin/serverchan/serverchan

**Comment by hong0980** [comment]
> > 还是那两个文件的权限没有改，改成755就能运行了。
> 
> 请问一下是哪两个文件需要改权限呢？我刚编译好 发现无法启动 也是mt7621平台

chmod 755 /etc/init.d/serverchan
chmod 755 /usr/bin/serverchan/serverchan

**Comment by XwbCHN** [comment]
感谢 已经成功使用

发自我的 iPhone

在 2019年8月15日，18:16，hong0980 <notifications@github.com<mailto:notifications@github.com>> 写道：


chmod 755 /etc/init.d/serverchan
chmod 755 /usr/bin/serverchan/serverchan
