### ISSUE TITLE
1.35-1.42版本均会出现wifi频繁提示连接断开

### ISSUE THREAD

**Issue by madman43** [tty228/luci-app-serverchan#61]
机型iphone8 连接5g信号频繁提示连接断开
在etc config  wireless 里面
wifi-iface下加
        option wpa_group_rekey '0'
        option wpa_pair_rekey '0'
        option wpa_master_rekey '0'
设置这个之后重启还是一样的，没有变化，但另外的安卓设备不设置好像都不提示，有点疑惑

**Comment by tty228** [comment]
你加大一下超时时间，苹果某些版本的系统，休眠省电很激进
我手上的 IOS12 不会休眠，不过老机子了，不太像升级系统测试
你顺便看看显示断开的时候管理页面上的 WiFi 连接还有没有显示，如果又显示的话，我下次加上 iw 命令验证
不过印象中 iw 命令跟系统日志会显示断开，不然当时应该不会用 ping 命令检测

**Comment by madman43** [comment]
朋友iphone7同样13.3.1系统不会这样频繁提示，提示断开的时候wifi界面连接都是显示的连接

**Comment by madman43** [comment]
今天到家重新打开推送看了下日志，因为我重新装过serverchan，不知道是不是这个原因，日志里面提示无法创建，不存在的目录，但编译集成上的固件也会提示这个
————————————————————————————————
Sat Mar 14 10:48:58 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 65: can't create : nonexistent directory
Sat Mar 14 10:48:58 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 813: can't create : nonexistent directory
Sat Mar 14 10:48:59 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:48:59 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:49:00 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:49:07 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 830: can't create : nonexistent directory
Sat Mar 14 10:49:08 2020 daemon.err uhttpd[2750]: cut: standard output: Broken pipe
Sat Mar 14 10:49:08 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 410: can't create : nonexistent directory
Sat Mar 14 10:49:08 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 411: can't create : nonexistent directory
Sat Mar 14 10:49:08 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 412: can't create : nonexistent directory
Sat Mar 14 10:49:54 2020 daemon.info hostapd: wlan0: STA  IEEE 802.11: associated
Sat Mar 14 10:49:54 2020 daemon.notice hostapd: STA not allowed to connect
Sat Mar 14 10:49:54 2020 daemon.info hostapd: wlan0: STA IEEE 802.11: disassociated
Sat Mar 14 10:49:54 2020 daemon.info hostapd: wlan0: STA  IEEE 802.11: disassociated
Sat Mar 14 10:50:00 2020 cron.info crond[13061]: USER root pid 15670 cmd /usr/share/UnblockNeteaseMusic/log_check.sh
Sat Mar 14 10:50:19 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:51:21 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:52:23 2020 daemon.err uhttpd[2750]: cut: standard output: Broken pipe
Sat Mar 14 10:52:23 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:53:01 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 555: can't create : nonexistent directory
Sat Mar 14 10:54:05 2020 kern.err /usr/bin/ssr-redir[27665]: server recv: Connection reset by peer
Sat Mar 14 10:54:11 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:54:12 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 486: can't create : nonexistent directory
Sat Mar 14 10:54:12 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:55:00 2020 cron.info crond[13061]: USER root pid 25869 cmd /usr/share/UnblockNeteaseMusic/log_check.sh
Sat Mar 14 10:55:13 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:55:51 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 555: can't create : nonexistent directory
Sat Mar 14 10:57:01 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:57:02 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 486: can't create : nonexistent directory
Sat Mar 14 10:57:02 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:58:04 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 10:58:42 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 555: can't create : nonexistent directory
Sat Mar 14 10:58:49 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 486: can't create : nonexistent directory
Sat Mar 14 10:58:49 2020 daemon.err uhttpd[2750]: command failed: No such device (-19)
Sat Mar 14 10:59:51 2020 daemon.err uhttpd[2750]: cut: standard output: Broken pipe
Sat Mar 14 10:59:51 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 11:00:00 2020 cron.info crond[13061]: USER root pid 2502 cmd /usr/share/UnblockNeteaseMusic/log_check.sh
Sat Mar 14 11:00:53 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 11:01:54 2020 daemon.err uhttpd[2750]: cut: standard output: Broken pipe
Sat Mar 14 11:01:54 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 380: can't create : nonexistent directory
Sat Mar 14 11:02:32 2020 daemon.err uhttpd[2750]: /usr/bin/serverchan/serverchan: line 555: can't create : nonexistent directory

**Comment by tty228** [comment]
你那个应该是日志文件无法写入
有打开日志选项吗
-----
![微信图片_20200315003750](https://user-images.githubusercontent.com/33397881/76686282-3f641b80-6655-11ea-9aee-0164618debb3.png)

试了一下 `iw` 并减少超时时间，果然是不行的

**Comment by madman43** [comment]
刚打开看了下，是这个样子，系统日志还是那些
————————————————————————
2020-03-15 09:54:51  【外网IP】正在检测外网IP变化
2020-03-15 09:54:51 【！！！】获取 IPv4 地址失败
2020-03-15 09:54:51  IPv6 无变化，当前 ipv6 为 240e:399:250:
2020-03-15 09:54:51  设备 unknown 192.168.2.20 依然坚挺
2020-03-15 09:55:29  【微信推送】设备 yeqingxin 192.168.2.181 断开连接 
2020-03-15 09:55:29  设备 yeqingxin 192.168.2.181 断开连接 
2020-03-15 09:55:37  设备 yeqingxin 192.168.2.181 连接失败
2020-03-15 09:55:37  没有新设备连接
2020-03-15 09:55:37 【负载】正在检测 CPU 负载
2020-03-15 09:55:37  CPU 负载正常：0.41
2020-03-15 09:55:37 【温度】正在检测 CPU 温度
2020-03-15 09:55:37  CPU 温度正常：68
2020-03-15 09:55:37  进行 URL 编码，标题=【K3】yeqingxin%20断开连接
2020-03-15 09:55:37 【等待】我累了，60 秒后再回来
2020-03-15 09:56:39  【外网IP】正在检测外网IP变化
2020-03-15 09:56:39 【！！！】获取 IPv4 地址失败
2020-03-15 09:56:39  IPv6 无变化，当前 ipv6 为 240e:399:250:
2020-03-15 09:56:39  设备 unknown 192.168.2.20 依然坚挺
2020-03-15 09:56:39  没有检测到设备离线
2020-03-15 09:56:39  【微信推送】新设备 yeqingxin 192.168.2.181 连接了
2020-03-15 09:56:39 新设备 yeqingxin 192.168.2.181 连接了
2020-03-15 09:56:39 【负载】正在检测 CPU 负载
2020-03-15 09:56:39  CPU 负载正常：0.30
2020-03-15 09:56:39 【温度】正在检测 CPU 温度
2020-03-15 09:56:39  CPU 温度正常：68
2020-03-15 09:56:39  进行 URL 编码，标题=【K3】yeqingxin%20连接了你的路由器
2020-03-15 09:56:40 【等待】我累了，60 秒后再回来

**Comment by jameyhhh** [comment]
您好，作者，请问 openwrt 主页概览里面 CPU温度才32度，为什么微信推送里的温度 是45度了，应该哪个更准确呢，谢谢！！

**Comment by tty228** [comment]
> 您好，作者，请问 openwrt 主页概览里面 CPU温度才32度，为什么微信推送里的温度 是45度了，应该哪个更准确呢，谢谢！！

不清楚你网页上的温度指令
脚本的温度获取是取所有传感器中，温度的最大值

详见： https://github.com/tty228/luci-app-serverchan/pull/41

如果想要自行修改，参考
https://github.com/tty228/luci-app-serverchan/issues/59

**Comment by tty228** [comment]
> pppoe

非多拨都是选的 pppoe 吧，实在不行就 URL 获取了，无法写入日志这个问题不知道出在哪里

**Comment by madman43** [comment]
1.46不频繁提示了。好像正常了
