### ISSUE TITLE
最新的源码我这死活启动不了

### ISSUE THREAD

**Issue by bin20088** [tty228/luci-app-serverchan#65]
打开日志报错前三行，关闭日志报错后两行。反正都启动不了
![QQ截图20200316033658](https://user-images.githubusercontent.com/53508344/76709184-980be500-6737-11ea-838d-130815a89a7d.jpg)

**Comment by bin20088** [comment]
Lean的源码X64固件

**Comment by tty228** [comment]
X64 是软路由吧，新版本主要是加了 iw 命令验证 WiFi 休眠设备，暂时用之前的版本吧
你命令行启动看看报什么错

**Comment by bin20088** [comment]
大佬方便的话可以加我QQ，方便及时配合你测试 ，争取早日完美 83887640

**Comment by asdertypo** [comment]
同样X86软路由，启动不了。
Mon Mar 16 20:01:28 2020 cron.info crond[28090]: crond (busybox 1.30.0) started, log level 5
Mon Mar 16 20:02:01 2020 cron.info crond[28592]: crond (busybox 1.30.0) started, log level 5
Mon Mar 16 20:02:46 2020 cron.info crond[29193]: crond (busybox 1.30.0) started, log level 5
Mon Mar 16 20:04:00 2020 cron.info crond[30013]: crond (busybox 1.30.0) started, log level 5

**Comment by bin20088** [comment]
> X64 是软路由吧，新版本主要是加了 iw 命令验证 WiFi 休眠设备，暂时用之前的版本吧
> 你命令行启动看看报什么错
命令行试了，不报错但显示runing，实际是没有运行的。有时候偶尔重启软路由能启动，但是立马提示网络不通，就再也不工作了。识别选择的接口pppoe-wan

**Comment by bin20088** [comment]
重启命令启动了  也有报错  但是网络不通就停了
![QQ截图20200317210030](https://user-images.githubusercontent.com/53508344/76858530-97d42c80-6892-11ea-8692-9d5c5dc3a3bc.jpg)

**Comment by bin20088** [comment]
完美解决。大佬幸苦
