### ISSUE TITLE
软路由openwrt 系统日志错误

### ISSUE THREAD

**Issue by beilsn** [tty228/luci-app-serverchan#66]
请教大佬我的软路由系统日志一直有如下错误，请教大佬怎么解决，多谢！  已解决！
Mon Mar 16 13:08:48 2020 daemon.err uhttpd[2616]: /usr/bin/serverchan/serverchan: line 1: arping: not found
Mon Mar 16 13:08:48 2020 daemon.err uhttpd[2616]: /usr/bin/serverchan/serverchan: line 1: arping: not found

**Comment by ZeaKyX** [comment]
> 请教大佬我的软路由系统日志一直有如下错误，请教大佬怎么解决，多谢！ 已解决！
> Mon Mar 16 13:08:48 2020 daemon.err uhttpd[2616]: /usr/bin/serverchan/serverchan: line 1: arping: not found
> Mon Mar 16 13:08:48 2020 daemon.err uhttpd[2616]: /usr/bin/serverchan/serverchan: line 1: arping: not found

不是写着`arping: not found`吗，你用的固件精简掉了？

**Comment by tty228** [comment]
`opkg update`
`opkg install curl`
`opkg install iputils-arping`

软路由不知道什么原因编译的时候会忽略依赖，手动安装吧

**Comment by beilsn** [comment]
> `opkg update`
> `opkg install curl`
> `opkg install iputils-arping`
> 
> 软路由不知道什么原因编译的时候会忽略依赖，手动安装吧

多谢大佬指点 已经搞定！
