### ISSUE TITLE
最新版本 lean源码

### ISSUE THREAD

**Issue by xiaozizi58** [tty228/luci-app-serverchan#68]
2020-03-22 21:46:02 【初始化】工作目录为 /tmp/serverchan/ 
2020-03-22 21:46:02 【初始化】log 目录为 /tmp/serverchan/serverchan.log 
2020-03-22 21:46:02 【初始化】未启用 MAC 过滤
2020-03-22 21:46:02 【初始化】载入在线设备
2020-03-22 21:46:03 【初始化】初始化完成
2020-03-22 21:46:03 【！！！！】当前网络不通！停止检测！ 
日志里
Sun Mar 22 21:43:58 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:44:58 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:45:50 2020 daemon.err /usr/bin/ss-redir[23244]: server recv: Connection reset by peer
Sun Mar 22 21:45:58 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:46:02 2020 cron.info crond[26982]: crond (busybox 1.30.0) started, log level 5
Sun Mar 22 21:46:02 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: arping: not found
Sun Mar 22 21:46:03 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:46:03 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:47:03 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:48:03 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found
Sun Mar 22 21:49:03 2020 daemon.err uhttpd[2611]: /usr/bin/serverchan/serverchan: line 1: curl: not found

是哪里的问题啊

**Comment by lysssssss** [comment]
curl: not found
