### ISSUE TITLE
静态IP的主机名识别还是有问题

### ISSUE THREAD

**Issue by kang-mk** [tty228/luci-app-serverchan#71]
![snipaste20200402_122312](https://user-images.githubusercontent.com/20243226/78210539-14931780-74dd-11ea-830a-015d5ec76e49.jpg)
![snipaste20200402_122410](https://user-images.githubusercontent.com/20243226/78210541-15c44480-74dd-11ea-9b3a-57cd972b5b73.jpg)

静态IP的设备serverchan无法识别，然后我在主机名里面指定了，serverchan依然还是获取不到，能不能直接读取“网络-主机名“下的名字

**Comment by kang-mk** [comment]
更新了之后还是识别不到，另外识别不到的这些都是固定ip的设备

**Comment by m2662m** [comment]
我的也是识别不了设备名字，很多unknown，不知能能不能识别成备注的主机名

**Comment by tty228** [comment]
1.60版本还显示吗

**Comment by kang-mk** [comment]
还是不行

**Comment by kang-mk** [comment]
移除 | luci-app-serverchan | 1.60-7
-- | -- | --

**Comment by tty228** [comment]
`nas_mac=***` #你静态设备MAC
``uci get dhcp.`uci show dhcp | grep -i ^dhcp.@host.*mac=.$nas_mac | sed -nr 's#^dhcp.(.*).mac.*#\1#gp'`.name``
你试试这个命令

**Comment by kang-mk** [comment]
uci: Invalid argument
参数无效？

**Comment by kang-mk** [comment]
![image](https://user-images.githubusercontent.com/20243226/79125074-1a87d300-7dd0-11ea-8c66-c0022da64d89.png)

**Comment by kang-mk** [comment]
移除 | uci | 2018-08-11-4c8b4d6e-1
-- | -- | --


软件包里面是有UCI的

**Comment by tty228** [comment]
![QQ截图20200413215130](https://user-images.githubusercontent.com/33397881/79125541-f4166780-7dd0-11ea-9932-5a003e15c41d.jpg)
![捕获](https://user-images.githubusercontent.com/33397881/79125552-f7115800-7dd0-11ea-9484-eba600036811.PNG)

这么诡异的吗，你运行 `uci show dhcp | grep -i ^dhcp.@host.*mac=.$nas_mac | sed -nr 's#^dhcp.(.*).mac.*#\1#gp'` 还有贴一下 `uci show` 的结果看看

**Comment by tty228** [comment]
话说插件自带的备注名也不能正常运行吗

**Comment by kang-mk** [comment]
![image](https://user-images.githubusercontent.com/20243226/79126323-4f952500-7dd2-11ea-9ba9-fb626b3f321a.png)
![image](https://user-images.githubusercontent.com/20243226/79126363-5e7bd780-7dd2-11ea-9f79-3548b5637767.png)

uci show dhcp 可以识别到静态IP

**Comment by kang-mk** [comment]
，你运行 uci show dhcp | grep -i ^dhcp.@host.*mac=.$nas_mac | sed -nr 's#^dhcp.(.*).mac.*#\1#gp' 
这个运行了什么也没显示

**Comment by tty228** [comment]
看到了，配置文件不一样

**Comment by kang-mk** [comment]
用的LEAN的源码编译的固件

**Comment by tty228** [comment]
[serverchan.zip](https://github.com/tty228/luci-app-serverchan/files/4469813/serverchan.zip)

你试试这个，覆盖 /usr/bin/serverchan ，0755权限

**Comment by kang-mk** [comment]
电脑已经关机了，只能明天再试了😁

**Comment by kang-mk** [comment]
我看你后来直接更新到源码了，直接刷机了昨晚编译的固件，1.62已经好了

**Comment by kang-mk** [comment]
定时推送回重复，而且其中一个的信息还不正常，手动推送正常

**Comment by tty228** [comment]
> 定时推送回重复，而且其中一个的信息还不正常，手动推送正常

1.62 还是 1.63，之前就发现有个主机名变量莫名其妙的不会自动清除，明明不是全局变量
1.63 我加了 unset

**Comment by kang-mk** [comment]
1.63的，1.62不清楚有没有这个问题，因为我昨天刷新了两三次固件，昨晚出问题之后看源码你更新到163了，然后我软件包里面也是163

**Comment by tty228** [comment]
把错误的推送内容发一下

**Comment by kang-mk** [comment]
https://anime.sinaapp.com/?c=wechat&a=read_push&readtoken=U12364R59c521fa2cc6b&pid=188937363


直接发给你链接吧

**Comment by tty228** [comment]
这个应该是 grep 忘了全字匹配

**Comment by kang-mk** [comment]
还继续在这个问题下面吧
这里在LEAN的固件下排版有问题   Lienol固件下正常  应该是luci版本不同造成的
![snipaste20200428_151125](https://user-images.githubusercontent.com/20243226/80458125-e7624980-8962-11ea-8993-ef8757c572a7.jpg)
