### ISSUE TITLE
启动后不久就停止运行

### ISSUE THREAD

**Issue by Quzard** [tty228/luci-app-serverchan#72]
![image](https://user-images.githubusercontent.com/30899719/78470122-6c3db700-7759-11ea-9a29-371c99f0f3b7.png)

**Comment by tty228** [comment]
发一下 /tmp/serverchan/ipAddress 文件的内容，可能读取到了错误的时间信息

**Comment by Quzard** [comment]
192.168.2.10 94:0e:6b:5b:aa:7f unknown 1586077106 br-lan
192.168.2.122 88:ae:07:2a:a6:61 IPAD 1586077106 br-lan
192.168.2.217 f8:28:19:6a:21:67 DESKTOP 1586077106 br-lan

**Comment by Quzard** [comment]
目测时间没问题

**Comment by tty228** [comment]
`sh -x /usr/bin/serverchan/serverchan`

这样运行一下，发一下退出之前的一段记录

**Comment by Quzard** [comment]
+ grep -v '^$'
+ awk '{print $6}'
+ grep -v '^$'
+ cat /proc/net/arp
+ sort+  -u
grep -w 192.168.2.217
+ local 'ip_name='
+ '[' -z  ]
+ local 'ip_name=unknown'
+ echo unknown
+ local 'ip_name=unknown'
+ getinterface 94:0e:6b:5b:aa:7f
+ '[' -f /tmp/serverchan/ipAddress ]
+ arping -I br-lan -c 20 -f+ grep -w -w 94:0e:6b:5b:aa:7f
 2 192.168.2.217
+ cat /tmp/serverchan/ipAddress
+ awk '{print $5}'
+ grep -v '^$'
+ sort -u
+ local 'ip_interface=br-lan'
+ '[' -f /tmp/serverchan/tmp_downlist ]
+ '[' -z br-lan ]
+ '[' '!' -z  ]
+ '[' -z br-lan ]
+ echo br-lan
+ local 'ip_interface=br-lan'
+ iw dev br-lan station dump
+ grep -i -w 94:0e:6b:5b:aa:7f
+ grep Station
+ local 'wlan_online='
+ cat /proc/net/arp
+ awk '{print $6}'
+ sort -u
+ grep -w 192.168.2.10
+ grep -v '^$'
+ arping -I br-lan -c 20 -f -w 2 192.168.2.10
+ echo ARPING 192.168.2.122 from 192.168.2.1 br-lan Unicast reply from 192.168.2.122 '[88:AE:07:2A:A6:61]' 26.706ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ local 'ip_ms=ARPING 192.168.2.122 from 192.168.2.1 br-lan Unicast reply from 192.168.2.122 [88:AE:07:2A:A6:61] 26.706ms Sent 1 probes (1 broadcast(s)) Received 1 response(s)'
+ '[' -z  ]
+ + echogrep ARPING -q 192.168.2.122 ms from
 192.168.2.1 br-lan Unicast reply from 192.168.2.122 '[88:AE:07:2A:A6:61]' 26.706ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ echo+ '[' '!' -z  ]
 ARPING 192.168.2.10 from 192.168.2.1 br-lan+  Unicast reply+  fromgrepecho ARPING -q 192.168.2.122 ms from
 192.168.2.1 br-lan Unicast reply from 192.168.2.122 '[88:AE:07:2A:A6:61]' 26.706ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
 192.168.2.10 '[94:0E:6B:5B:AA:7F]' 1.011ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ local 'ip_ms=ARPING 192.168.2.10 from 192.168.2.1 br-lan Unicast reply from 192.168.2.10 [94:0E:6B:5B:AA:7F] 1.011ms Sent 1 probes (1 broadcast(s)) Received 1 response(s)'
+ '[' -z  ]
+ '['+ echo ARPING 192.168.2.10 from 192.168.2.1 br-lan Unicast reply from 192.168.2.10+ grep '[94:0E:6B:5B:AA:7F]' -q ms
 1.011ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
 '!' -z 2 ]
+ '[' 2 -ne 1 ]
+ '[' '!' -z  ]
+ date '+%Y-%m-%d %H:%M:%S'
+ grep -q ms
+ echo ARPING 192.168.2.10 from+  192.168.2.1echo '2020-04-05 17:03:50  设备 IPAD 192.168.2.122 依然坚挺'
+ echo 
 br-lan Unicast reply from 192.168.2.10 '[94:0E:6B:5B:AA:7F]' 1.011ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ '[' '!' -z 2 ]
+ '[' 2 -ne 1 ]
+ date '+%Y-%m-%d %H:%M:%S'
+ echo '2020-04-05 17:03:50  设备 unknown 192.168.2.10 依然坚挺'
+ echo 
+ echo ARPING 192.168.2.217 from 192.168.2.1 br-lan Unicast reply from 192.168.2.217 '[F8:28:19:6A:21:67]' 101.176ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ local 'ip_ms=ARPING 192.168.2.217 from 192.168.2.1 br-lan Unicast reply from 192.168.2.217 [F8:28:19:6A:21:67] 101.176ms Sent 1 probes (1 broadcast(s)) Received 1 response(s)'
+ '[' -z  ]
+ echo ARPING 192.168.2.217+  fromgrep 192.168.2.1 -q br-lan ms Unicast
 reply from 192.168.2.217 '[F8:28:19:6A:21:67]' 101.176ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ '[' '!' -z  ]
+ echo+  ARPINGgrep 192.168.2.217 -q from ms 192.168.2.1
 br-lan Unicast reply from 192.168.2.217 '[F8:28:19:6A:21:67]' 101.176ms Sent 1 probes '(1' 'broadcast(s))' Received 1 'response(s)'
+ '[' '!' -z 2 ]
+ '[' 2 -ne 1 ]
+ date '+%Y-%m-%d %H:%M:%S'
+ echo '2020-04-05 17:03:51  设备 DESKTOP 192.168.2.217 依然坚挺'
+ echo 
+ '[' '!' -f /tmp/serverchan/ipAddress ]
+ grep -c  /tmp/serverchan/ipAddress
+ '[' 3 -eq 3 ]
+ '[' '!' -z 2 ]
+ '[' 2 -ne 1 ]
+ date '+%Y-%m-%d %H:%M:%S'
+ echo '2020-04-05 17:03:51  没有检测到设备离线'
+ unset IPLIST
+ unset IPLISTrow
+ '[' '!' -f /tmp/serverchan/ipAddress ]
+ cat /proc/net/arp
+ grep '0x2\|0x6'
+ awk '{print $1}'
+ grep -v '^$'
+ sort -u
+ IPLIST='192.168.2.10
192.168.2.122
192.168.2.217'
+ grep -c  /tmp/serverchan/ipAddress
+ IPLISTrow=3
+ get_config send_enable
+ '[' send_enable ]
+ uci get serverchan.serverchan.send_enable
+ send_enable=0
+ '[' '!' -z 192.168.2.10 ]
+ '[' 0 -ne 3 ]
+ read -u 5
+ '[' '!' -z 192.168.2.122+  ]up
 192.168.2.10
+ '['+  192.168.2.10'[' ] 0
 -ne 3 ]
+ read -u 5
+ '[' '!' -z 192.168.2.217 ]
+ up 192.168.2.122
+ + '[''[' 0 -ne 3 ] 192.168.2.122
 ]
+ read -u 5
+ wait
+ cat /tmp/serverchan/ipAddress
+ up 192.168.2.217
+ grep -w 192.168.2.10
+ grep -w 192.168.2.122
+ '[' 192.168.2.217 ]
+ cat /tmp/serverchan/ipAddress
+ cat /tmp/serverchan/ipAddress
+ grep -w 192.168.2.217
+ local 'ip=192.168.2.122 88:ae:07:2a:a6:61 IPAD 1586077429 br-lan'
+ '[' -z '192.168.2.122 88:ae:07:2a:a6:61 IPAD 1586077429 br-lan' ]
+ echo 
+ local 'ip=192.168.2.10 94:0e:6b:5b:aa:7f unknown 1586077428 br-lan'
+ '[' -z '192.168.2.10 94:0e:6b:5b:aa:7f unknown 1586077428 br-lan' ]
+ + localecho 'ip=192.168.2.217 f8:28:19:6a:21:67 DESKTOP 1586077428 br-lan' 

+ '[' -z '192.168.2.217 f8:28:19:6a:21:67 DESKTOP 1586077428 br-lan' ]
+ echo 
+ '[' '!' -f /tmp/serverchan/ipAddress ]
+ grep -c  /tmp/serverchan/ipAddress
+ '[' 3 -eq 3 ]
+ '[' '!' -z 2 ]
+ '[' 2 -ne 1 ]
+ date '+%Y-%m-%d %H:%M:%S'
+ echo '2020-04-05 17:03:51  没有新设备连接'
+ unset IPLIST
+ unset IPLISTrow
+ down_send
+ '[' '!' -f /tmp/serverchan/tmp_downlist ]
+ cat /tmp/serverchan/tmp_downlist
+ awk '{print $1}'
+ local 'IPLIST=1586065854'
+ '[' '!' -z 1586065854 ]
+ cat /tmp/serverchan/tmp_downlist
+ grep -w 1586065854
+ awk '{print $2}'
+ grep -v '^$'
+ sort -u
+ local 'ip_mac=br-lan'
+ cat /tmp/serverchan/tmp_downlist
+ grep -w 1586065854
+ awk '{print $3}'
+ sort -u
+ grep -v '^$'
+ local 'ip_name='
+ cat /tmp/serverchan/tmp_downlist
+ grep -w 1586065854+ + sortawk -u '{print $4}'

+ grep -v '^$'

+ local 'ip_uptime='
+ + grep -w 1586065854
cat /tmp/serverchan/tmp_downlist
+ sort -u
+ grep -v '^$'
+ awk '{print $5}'
+ local 'ip_interface='
+ '[' '!' -z 1 ]
+ '[' 1 -eq 1 ]
+ blackwhitelist br-lan
+ '[' br-lan ]
+ '[' -z  ]
+ '[' -z  ]
+ '[' -z  ]
+ echo 1
+ local 'ip_blackwhite=1'
+ '[' '!' -z 1 ]
+ '[' 1 -eq 1 ]
+ '[' -f /tmp/serverchan/title ]
+ '[' -f /tmp/serverchan/content ]
+ usage_ip 1586065854
+ '[' 1586065854 ]
+ '[' -f /tmp/serverchan/usage.db ]
+ cat /tmp/serverchan/usage.db+ grep -w 1586065854

+ local 'ip='
+ '[' '!' -z  ]
+ '[' '!' -z  ]
+ local 'ip_total='
+ '[' '!' -z  ]
+ date '+%s'
+ local 'time_down=1586077431'
/usr/bin/serverchan/serverchan: line 810: arithmetic syntax error

**Comment by Quzard** [comment]
ip_uptime应该没获取到貌似

**Comment by tty228** [comment]
删除 /tmp/serverchan/tmp_downlist 文件
应该是不知为何写入了错误的信息，然后启动的时候没有清理掉

**Comment by tty228** [comment]
删除之前发一下里面的内容

**Comment by Quzard** [comment]
嗯好，谢谢，我试试

**Comment by tty228** [comment]
tmp_downlist 文件里面 ip 应该是空的，可能哪里把判断式漏掉了

**Comment by Quzard** [comment]
谢谢你的回复，问题应该已经解决
