### ISSUE TITLE
希望无人值守能添加WIFI重启功能。

### ISSUE THREAD

**Issue by kkss2020** [tty228/luci-app-serverchan#73]
路由器有时候断电重启够会不启动WIFI，必须在设置里重新启动路由器才行。但是家里用的都是AP很是烦恼。。希望能推出这个功能万分感谢。

**Comment by tty228** [comment]
路由器启动的时候不会启动WiFi？
现在无人值守任务只会在系统或网络在线时间大于设定值的时候才会重启，如果是路由器重启不会启动WiFi，建议在启动项中加入命令 `wifi up`

**Comment by kkss2020** [comment]
tanks
