### ISSUE TITLE
ip变动通知的问题

### ISSUE THREAD

**Issue by lcckis** [tty228/luci-app-serverchan#75]
ip变动或者重启的时候只发一个当前ip通知，能否让ip变动通知的格式和定时推送中wan信息的格式一样？ 不仅有接口ip还有外网ip信息，排版还好看。

**Comment by tty228** [comment]
排版起来很头疼
先要设计好 MarkDown 排版，然后 URL 转码，还要对齐，中文占 3 个字符，实际显示只占用 2 个字符宽度
调试起来特别麻烦，加上没啥美术细胞，感觉就像个烂摊子，不想碰

**Comment by lcckis** [comment]
> 标记起来很头疼先要
> 设计好的MarkDown布局，然后URL转码，还要对齐，中文占3个字符，实际显示只占用2个
> 字符宽度调试起来特别麻烦，加上没啥美术细胞，感觉就像个烂摊子，不想碰

不能直接调用wan信息的排版吗，ip发生变动直接改成单独发送wan口信息....................

**Comment by tty228** [comment]
> > 标记起来很头疼先要
> > 设计好的MarkDown布局，然后URL转码，还要对齐，中文占3个字符，实际显示只占用2个
> > 字符宽度调试起来特别麻烦，加上没啥美术细胞，感觉就像个烂摊子，不想碰
> 
> 不能直接调用wan信息的排版吗，ip发生变动直接改成单独发送wan口信息....................

因为一开始打算很简单的做个脚本，没想到加了这么多功能，代码结构比较乱，wan口信息 其实是在定时发送的 function 里，并没有独立出来
然后现在要改的话，检测 ip+上线+离线+当前设备+cpu 状态都要重新改

有空再说吧……

**Comment by tty228** [comment]
本来想下午改一下的，ddns很不靠谱啊，测试重拨功能，结果ddns没重新解析，serverchan又免打扰
连不上路由器了
