### ISSUE TITLE
竞斗云安装后，不能使用

### ISSUE THREAD

**Issue by stephenlzc** [tty228/luci-app-serverchan#79]
广东电信，公网IP，安装luci-app-serverchan_1.60-7_all.ipk后，提示重启，然后点开后提示如下信息

/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/serverchan'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/network.lua:349: attempt to call field 'checkmac' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

请问就当如何处理？

**Comment by tty228** [comment]
试试删除配置文件重新安装

**Comment by stephenlzc** [comment]
删除路由的配置文件吗？有具体操作指南吗？谢谢！

**Comment by tty228** [comment]
使用 https://github.com/tty228/luci-app-serverchan/blob/master/root/etc/config/serverchan
覆盖 /etc/config/serverchan 试试，不行重装，不明原因
