### ISSUE TITLE
多拨后无法检测外网IP，导致不停推送路由器重启通知

### ISSUE THREAD

**Issue by bin20088** [tty228/luci-app-serverchan#8]
我提个建议呗。就拿我的网络环境来说，我是X86，设置双拨后，出现虚拟wan口，分别是vwan1和vwan2，双拨后的wan口是禁用的， 就没有IP地址，所以检测不到IP就会不停的推送路由器重启的通知。可不可以增加个选项，手动选择外网ip检测来源，比如eth0、eth1、eth2。这样不管是否多拨，只要自己设置好来源接口，都可以完美应对。
另外一个问题，就是启动不了。也是看了你的issues后，改了那俩文件的权限，就正常了。

**Comment by bin20088** [comment]
如果根据MAC地址来判断，也不好弄。双拨后虚拟口vwan1和vwan2的mac地址都是00:00:00:00:00.还不能手动修改。还有那个设备别名的mac也是没法填。

**Comment by tty228** [comment]
多拨环境不太了解，如果要自己修改的话，
552行
#查询当前ip
#hostIP=$(curl -k -s  "http://members.3322.org/dyndns/getip")
wanIP=$(ubus call network.interface.wan status | grep '\"address\"' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')

注释掉的是通过网站查询ip，现用的是wan接口

**Comment by leungzw** [comment]
> 
> 
> 我提个建议呗。就拿我的网络环境来说，我是X86，设置双拨后，出现虚拟wan口，分别是vwan1和vwan2，双拨后的wan口是禁用的， 就没有IP地址，所以检测不到IP就会不停的推送路由器重启的通知。可不可以增加个选项，手动选择外网ip检测来源，比如eth0、eth1、eth2。这样不管是否多拨，只要自己设置好来源接口，都可以完美应对。
> 另外一个问题，就是启动不了。也是看了你的issues后，改了那俩文件的权限，就正常了。

试了多拨后同样的问题，取消了多拨也恢复不了。怎样解决？

**Comment by tty228** [comment]
请暂时关闭 ip 变动检测，没有多拨环境不打算修复
