### ISSUE TITLE
系统日志频繁出现/usr/bin/serverchan/serverchan: line 1: iw: not found

### ISSUE THREAD

**Issue by 1049066154** [tty228/luci-app-serverchan#80]
设备:
    斐讯N1
系统:
    Lean大佬最新代码编译,Docker容器运行
系统日志:
Mon Apr 13 20:36:08 2020 daemon.err uhttpd[1596]: /usr/bin/serverchan/serverchan: line 1: iw: not found
Mon Apr 13 20:36:08 2020 daemon.err uhttpd[1596]: /usr/bin/serverchan/serverchan: line 1: iw: not found
Mon Apr 13 20:36:08 2020 daemon.err uhttpd[1596]: /usr/bin/serverchan/serverchan: line 1: iw: not found
Mon Apr 13 20:36:08 2020 daemon.err uhttpd[1596]: /usr/bin/serverchan/serverchan: line 1: iw: not found
Mon Apr 13 20:36:08 2020 daemon.err uhttpd[1596]: /usr/bin/serverchan/serverchan: line 1: iw: not found
,运行时一直报这个错误,功能上功能没发现啥问题,客户端开调试日志也没有啥异常

**Comment by tty228** [comment]
iw 命令是无线设备管理用的，我还以为都会默认安装的
然后忽略错误信息的命令没写好，我改一下吧

**Comment by 1049066154** [comment]
> iw 命令是无线设备管理用的，我还以为都会默认安装的
> 然后忽略错误信息的命令没写好，我改一下吧
> 不过没有 iw 命令可能会频繁推送设备休眠离线，增大离线检测时间吧
因为我用的是旁路由，没有wifi功能，所以接入设备都是在主路由的wifi和lan口上
