### ISSUE TITLE
iPhone 8 plus频繁推送！

### ISSUE THREAD

**Issue by WXfeng-boy** [tty228/luci-app-serverchan#83]
我的iPhone 8 plus会隔一段时间就会出现断开 连接 断开 连接，从ap里看了下连接时间，没有断连

**Comment by leo8912** [comment]
好像苹果的都会这样，我8和8p都有这种情况，不知道是不是息屏wifi就断了？

**Comment by jaove** [comment]
苹果手机不插电源就会出现频繁断线/上线推送，但是插着电源就不会推送，可能是ios系统对wifi的电源管理模式导致的。

**Comment by liwenjie119** [comment]
所以能否整一下，屏蔽掉特定设备的推送消息？

**Comment by liwenjie119** [comment]
> 所以能否整一下，屏蔽掉特定设备的推送消息？

突然发现有mac过滤

**Comment by liwenjie119** [comment]
> > 所以能否整一下，屏蔽掉特定设备的推送消息？
> 
> 突然发现有mac过滤

不过这个过滤是免打扰的过滤吗？还是全局推送过滤？
