### ISSUE TITLE
V1.78版本BUG

### ISSUE THREAD

**Issue by 755549488** [tty228/luci-app-serverchan#86]
实测在openwrt1907版本安装后无法启动，显示serverchan未运行。

**Comment by FANminiworld** [comment]
请贴 log

**Comment by Yuyuko-sama** [comment]
log错误是：
未安装wrtbwmon,流量统计不可用
依赖项未安装
读取设置出错，请检查设置项

就这几行，一直启动不了+1 QAQ

**Comment by 755549488** [comment]
> 请贴 log

log错误是：
未安装wrtbwmon,流量统计不可用
依赖项未安装
读取设置出错，请检查设置项

就这几行，一直启动不了+1 QAQ

的确如3楼所说 我的情况跟3楼一样

**Comment by tty228** [comment]
1.75之后，luci 使用 uci-defaults 方式保存设置与启动，安装后需要重启或者直接编译
ssh 运行`/root/etc/uci-defaults/luci-serverchan`（大概也可以）

**Comment by 755549488** [comment]
> 1.75之后，luci 使用 uci-defaults 方式保存设置与启动，安装后需要重启或者直接编译
> ssh 运行`/root/etc/uci-defaults/luci-serverchan`（大概也可以）

我这个路径下面是空的 /root/etc/uci-defaults

**Comment by 755549488** [comment]
> 1.75之后，luci 使用 uci-defaults 方式保存设置与启动，安装后需要重启或者直接编译
> ssh 运行`/root/etc/uci-defaults/luci-serverchan`（大概也可以）

试了 重启也无效

**Comment by beck023** [comment]
L大源码编译的：OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)
同样报错无法运行，
log:
未安装wrtbwmon,流量统计不可用
依赖项未安装
读取设置出错，请检查设置项
试过重启路由或重启服务，都不行。

**Comment by aixufan** [comment]
楼上几个不看安装教程么，都是依赖插件没装
