### ISSUE TITLE
潘多拉20.03安装后出现如下错误

### ISSUE THREAD

**Issue by iori8421** [tty228/luci-app-serverchan#88]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/services/serverchan/client'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/simpleform'.
A runtime error occured: /usr/lib/lua/luci/template.lua:39: Failed to load template 'serverchan/client'.
Error while parsing template '/usr/lib/lua/luci/view/serverchan/client.htm':
No such file or directory
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by newborn2010** [comment]
是啊，肿么解决？

**Comment by tty228** [comment]
client.lua 用于查看设备列表和流量信息
自行删除相关字段 https://github.com/tty228/luci-app-serverchan/search?q=client
或使用 1.78 以前的版本
