### ISSUE TITLE
关于设备别名发现的两个问题

### ISSUE THREAD

**Issue by liyuhaolol** [tty228/luci-app-serverchan#89]
- 1.如果ap不重启，op的主路由重启了，那么所有连接ap的设备，包括ap本身。在在线设备里，大概率被识别为unknown，只有当这些设备与路由器断开连接一段时间，重连。才能恢复，不知道是不是BUG。
- 2.设备别名里不带带有“空格”和“-”，如果有这两个字符，那么别名会在这个位置截断。如果是稳定性考虑，不支持“空格”的话，“-”也不支持是不是有点奇怪啊。如果能希望两个都支持！

希望能就这俩问题得到一个回答。

**Comment by tty228** [comment]
1. 96行的注释取消掉就行了
2.这个是遗留问题，一开始应该设置为,分隔MAC跟设备名，但是脑抽用了-，后来再改的话，会造成配置文件失效，所以懒得改了

**Comment by liyuhaolol** [comment]
> 1. 96行的注释取消掉就行了
> 2. 这个是遗留问题，一开始应该设置为,分隔MAC跟设备名，但是脑抽用了-，现在再改的话，会造成之前的设备别名需要重新设置，所以懒得改了，需要修改的话，在19行

1.96行如果解开注释，会有什么负面效果呢？当时为何要注释掉这个东西？
2.我看19行的代码，如果改成这样，去掉g，不全局生效，只生效第一个位置，是不是就可以很好的解决这个问题了呢？当然改成","是个比较好选择。
```shell
#原来的语句
device_aliases=`echo "$device_aliases"|sed 's/ /\n/g'|sed 's/-/ /g'` 2>/dev/null
#修改后的语句
device_aliases=`echo "$device_aliases"|sed 's/ /\n/g'|sed 's/-/ /'` 2>/dev/null
```

**Comment by tty228** [comment]
因为大部分情况下，重复读取并不能获取正确的设备名，浪费时间跟系统资源
设置了设备别名的情况下，只要正确获取了 MAC ，应该不会识别成 unknown 吧
如果识别成 unknown ，那就是 bug 了

2. 代码可用

**Comment by tujj99** [comment]
同样的问题1，luci里面设置了备注，如果不重启永远显示的是unknown，重启后正常。
