### ISSUE TITLE
不能启动问题，源码里就把那两个文件改了权限就没问题

### ISSUE THREAD

**Issue by bin20088** [tty228/luci-app-serverchan#9]
亲测。拉完源码就直接在源码里把下面两个文件改了权限编译出来就没问题。
/etc/init.d/serverchan
/usr/bin/serverchan/serverchan

**Comment by andrewstar** [comment]
看来这个问题还是没有修复，今天编译出来也是不能执行，编译之后加了执行权限，也不行，后来从另外一个源里面直接拷贝一个过去再编译就能成功运行了
