### ISSUE TITLE
最近没什么时间维护代码

### ISSUE THREAD

**Issue by tty228** [tty228/luci-app-serverchan#91]
辞职返乡，电脑快递回家了
新工作大概要住一段时间宿舍，应该是没有电脑用了

遇到问题的尽量搜索吧

**Comment by mjyhj** [comment]
大雕源码5.4内核编译不了

**Comment by jw10126121** [comment]
> 大雕源码5.4内核编译不了

我昨天编译R3G和RM2100，是可以编译通过的。。   还没刷入

**Comment by makeye** [comment]
哥，用不了了。openwrt调用直接调用不了了，点击直接网站都打不开，直接浏览器输网址，是另外一个东西。麻烦你修复下
