### ISSUE TITLE
关于5.4内核不能启用serverchan的问题

### ISSUE THREAD

**Issue by lll9p** [tty228/luci-app-serverchan#92]
编辑文件：

/usr/share/rpcd/acl.d/luci-app-serverchan.json

设置权限为：644

内容为：
`{
        "luci-app-serverchan": {
                "description": "Grant access to serverchan executables",
                "read": {
                        "uci": [ "serverchan" ]
                },
                "write": {
                        "uci": [ "serverchan" ]
                }
        }
}`

重启即可运行。

**Comment by mjyhj** [comment]
3Q

**Comment by Aziiiiiiiiiiiii** [comment]
不行呀。我放弃了
