### ISSUE TITLE
我想需要一项新功能，望开发

### ISSUE THREAD

**Issue by anbell2** [tty228/luci-app-serverchan#94]
最近上班被老板用海康威视摄像头+录像机远程监控，很不爽。他能随时远程看。我想知道的是他什么时候在看。实现原理，我用路由器监控录像机的上传网速，一旦录像机有上传，表示老板在远程看监控。望开发，谢谢。

**Comment by tty228** [comment]
路由器都在你手上了，还怕不知道老板在看监控吗
转发一个假的啊（手动滑稽）
现在手上两台路由器都不能检测到流量，不好测试

**Comment by tty228** [comment]
功能已更新
