### ISSUE TITLE
IP地址没有变动还老推送

### ISSUE THREAD

**Issue by snake94115** [tty228/luci-app-serverchan#95]
从7月30日开始IP地址没有变动还推送，每隔大概20分钟推送一回，原来是只有地址变动才推送，设置我什么都没动过，请教一下，是我网的问题吗？

**Comment by naoki66** [comment]
IP 地址变化

 当前 IP：502 Bad Gateway
The server returned an invalid or incomplete response.


主要是因为接口不稳定造成的

**Comment by snake94115** [comment]
> 服务器返回了无效或不完整的响应。

是这个提示，请教一下，接口不稳，是我自己网络这头问题吗？

**Comment by tty228** [comment]
自行更换 URL，或者使用接口 获取
