### ISSUE TITLE
新版本微信推送IP变动几分推送一次

### ISSUE THREAD

**Issue by long95588** [tty228/luci-app-serverchan#96]
你好:新版本微信推送是不是有问题，我设置3小时定时推送一次，公网IP三天都没有变动。几分钟就推送一次IP变动信息。以前版本没有这样问题。
![Screenshot_2020-07-31-10-44-25-110_com tencent mm](https://user-images.githubusercontent.com/57219722/88994446-f74f4800-d31a-11ea-914d-d143478b125e.jpg)

**Comment by snake94115** [comment]
是不是每隔20分钟左右就推送一次IP地址？

**Comment by ff522** [comment]
这个获取ip的接口不稳定了

有没有可以更换的

**Comment by sysnxw** [comment]
我也遇到了，没办法，只能暂时关闭这个功能了。
