### ISSUE TITLE
支持 ServerChan·测试号版发送消息

### ISSUE THREAD

**Issue by easychen** [tty228/luci-app-serverchan#98]
ServerChan新增了通过测试号推送的版本（ https://sct.ftqq.com/ ）可以直接在消息卡片中显示内容，API 和原来的公众号版兼容，但是域名不同。

可以直接根据 sendkey 前缀判断版本：

- 测试号 sendkey 开头：SCT ， 对应域名：sctapi.ftqq.com
- 公众号版本 sckey 开头：SCU ，对应域名：sc.ftqq.com

可在 /root/usr/bin/serverchan/serverchan 中判断 key 并替换对应的域名。

本来我想改改，但是没有测试环境，不好测试……

**Comment by harleywong** [comment]
![微信图片_20200827210049](https://user-images.githubusercontent.com/34861262/91445266-7c8d3480-e8a8-11ea-9679-3a5f35106a15.jpg)
![微信图片_20200827210056](https://user-images.githubusercontent.com/34861262/91445278-7e56f800-e8a8-11ea-944c-ddac6abd2dfb.jpg)
用树莓派的openwrt试了一下，改了/usr/bin/serverchan/serverchan 中的网址，在luci里面替换了测试版key。可以推送，但是可能是少了什么字段，不进详情的话内容显示“---”

**Comment by easychen** [comment]
> ![微信图片_20200827210049](https://user-images.githubusercontent.com/34861262/91445266-7c8d3480-e8a8-11ea-9679-3a5f35106a15.jpg)
> ![微信图片_20200827210056](https://user-images.githubusercontent.com/34861262/91445278-7e56f800-e8a8-11ea-944c-ddac6abd2dfb.jpg)
> 用树莓派的openwrt试了一下，改了/usr/bin/serverchan/serverchan 中的网址，在luci里面替换了测试版key。可以推送，但是可能是少了什么字段，不进详情的话内容显示“---”

这个没少字段，是因为消息卡片上的 markdown 没有渲染，然后截断了… 
我想想要不要处理下过滤下格式啊…
